// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, is_admin, created_at, disabled_at
FROM accounts
WHERE id = $1
`

type GetAccountByIDRow struct {
	ID         uuid.UUID
	Email      string
	IsAdmin    bool
	CreatedAt  time.Time
	DisabledAt *time.Time
}

// Scoped by id as the primary defence (L12); the RLS policy on accounts is the backstop
// underneath it. Always called through tenancy.InTx.
func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}
