// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"

	uuid "github.com/google/uuid"
)

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, is_admin, created_at, disabled_at
FROM accounts
WHERE id = $1
`

// Scoped by id as the primary defence (L12); the RLS policy on accounts is the backstop
// underneath it. Always called through tenancy.InTx.
func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}
