// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (
  account_id, name, metric, scope_kind, scope_name, comparator,
  trigger_at, clear_at, cooldown_seconds, enabled
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9, $10
)
RETURNING id
`

type CreateAlertRuleParams struct {
	AccountID       uuid.UUID
	Name            string
	Metric          string
	ScopeKind       string
	ScopeName       string
	Comparator      string
	TriggerAt       decimal.Decimal
	ClearAt         decimal.Decimal
	CooldownSeconds int32
	Enabled         bool
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.AccountID,
		arg.Name,
		arg.Metric,
		arg.ScopeKind,
		arg.ScopeName,
		arg.Comparator,
		arg.TriggerAt,
		arg.ClearAt,
		arg.CooldownSeconds,
		arg.Enabled,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertAlert = `-- name: InsertAlert :one
INSERT INTO alerts (
  account_id, rule_id, kind, metric, scope_kind, scope_name, value, run_id, fired_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9
)
RETURNING id
`

type InsertAlertParams struct {
	AccountID uuid.UUID
	RuleID    uuid.UUID
	Kind      string
	Metric    string
	ScopeKind string
	ScopeName string
	Value     decimal.NullDecimal
	RunID     *int64
	FiredAt   time.Time
}

// The record, written whether or not the message ever leaves the building: delivery is
// transport, and an account whose channel expired still has a history of what happened while
// nobody was being told.
func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAlert,
		arg.AccountID,
		arg.RuleID,
		arg.Kind,
		arg.Metric,
		arg.ScopeKind,
		arg.ScopeName,
		arg.Value,
		arg.RunID,
		arg.FiredAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT r.id, r.name, r.metric, r.scope_kind, r.scope_name, r.comparator,
       r.trigger_at, r.clear_at, r.cooldown_seconds, r.enabled, r.created_at,
       s.firing, s.since, s.last_fired_at
FROM alert_rules r
LEFT JOIN alert_state s ON s.rule_id = r.id
WHERE r.account_id = $1
ORDER BY r.name
`

type ListAlertRulesRow struct {
	ID              uuid.UUID
	Name            string
	Metric          string
	ScopeKind       string
	ScopeName       string
	Comparator      string
	TriggerAt       decimal.Decimal
	ClearAt         decimal.Decimal
	CooldownSeconds int32
	Enabled         bool
	CreatedAt       time.Time
	Firing          *bool
	Since           *time.Time
	LastFiredAt     *time.Time
}

// account_id is the primary defence (L12); RLS is the backstop underneath it.
func (q *Queries) ListAlertRules(ctx context.Context, accountID uuid.UUID) ([]ListAlertRulesRow, error) {
	rows, err := q.db.Query(ctx, listAlertRules, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertRulesRow{}
	for rows.Next() {
		var i ListAlertRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metric,
			&i.ScopeKind,
			&i.ScopeName,
			&i.Comparator,
			&i.TriggerAt,
			&i.ClearAt,
			&i.CooldownSeconds,
			&i.Enabled,
			&i.CreatedAt,
			&i.Firing,
			&i.Since,
			&i.LastFiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT a.id, a.rule_id, r.name AS rule_name, a.kind, a.metric, a.scope_kind, a.scope_name,
       a.value, a.run_id, a.fired_at, a.delivered_at, a.delivery_error
FROM alerts a
JOIN alert_rules r ON r.id = a.rule_id
WHERE a.account_id = $1
ORDER BY a.fired_at DESC
LIMIT $2
`

type ListAlertsParams struct {
	AccountID uuid.UUID
	MaxRows   int32
}

type ListAlertsRow struct {
	ID            uuid.UUID
	RuleID        uuid.UUID
	RuleName      string
	Kind          string
	Metric        string
	ScopeKind     string
	ScopeName     string
	Value         decimal.NullDecimal
	RunID         *int64
	FiredAt       time.Time
	DeliveredAt   *time.Time
	DeliveryError *string
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.AccountID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsRow{}
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.RuleName,
			&i.Kind,
			&i.Metric,
			&i.ScopeKind,
			&i.ScopeName,
			&i.Value,
			&i.RunID,
			&i.FiredAt,
			&i.DeliveredAt,
			&i.DeliveryError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertDelivered = `-- name: MarkAlertDelivered :exec
UPDATE alerts SET delivered_at = $1, delivery_error = NULL
WHERE account_id = $2 AND id = $3
`

type MarkAlertDeliveredParams struct {
	DeliveredAt *time.Time
	AccountID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) MarkAlertDelivered(ctx context.Context, arg MarkAlertDeliveredParams) error {
	_, err := q.db.Exec(ctx, markAlertDelivered, arg.DeliveredAt, arg.AccountID, arg.ID)
	return err
}

const markAlertUndelivered = `-- name: MarkAlertUndelivered :exec
UPDATE alerts SET delivery_error = $1
WHERE account_id = $2 AND id = $3
`

type MarkAlertUndeliveredParams struct {
	DeliveryError *string
	AccountID     uuid.UUID
	ID            uuid.UUID
}

// The error is written by a caller that has already redacted it: whatever went wrong with a
// channel, the channel's own credential is not what goes in this column (L13).
func (q *Queries) MarkAlertUndelivered(ctx context.Context, arg MarkAlertUndeliveredParams) error {
	_, err := q.db.Exec(ctx, markAlertUndelivered, arg.DeliveryError, arg.AccountID, arg.ID)
	return err
}

const updateAlertRule = `-- name: UpdateAlertRule :execrows
UPDATE alert_rules SET
  name = $1,
  comparator = $2,
  trigger_at = $3,
  clear_at = $4,
  cooldown_seconds = $5,
  enabled = $6
WHERE account_id = $7 AND id = $8
`

type UpdateAlertRuleParams struct {
	Name            string
	Comparator      string
	TriggerAt       decimal.Decimal
	ClearAt         decimal.Decimal
	CooldownSeconds int32
	Enabled         bool
	AccountID       uuid.UUID
	ID              uuid.UUID
}

// The thresholds are the whole of what a user tunes, so an update replaces them together: a
// trigger changed without its clear line is how a band ends up pointing the wrong way, and
// the schema would then refuse the write with no obvious cause.
func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAlertRule,
		arg.Name,
		arg.Comparator,
		arg.TriggerAt,
		arg.ClearAt,
		arg.CooldownSeconds,
		arg.Enabled,
		arg.AccountID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAlertState = `-- name: UpsertAlertState :exec
INSERT INTO alert_state (rule_id, account_id, firing, since, last_fired_at)
VALUES ($1, $2, $3, $4,
        $5)
ON CONFLICT (rule_id) DO UPDATE SET
  firing = EXCLUDED.firing,
  since = EXCLUDED.since,
  last_fired_at = EXCLUDED.last_fired_at
`

type UpsertAlertStateParams struct {
	RuleID      uuid.UUID
	AccountID   uuid.UUID
	Firing      bool
	Since       *time.Time
	LastFiredAt *time.Time
}

func (q *Queries) UpsertAlertState(ctx context.Context, arg UpsertAlertStateParams) error {
	_, err := q.db.Exec(ctx, upsertAlertState,
		arg.RuleID,
		arg.AccountID,
		arg.Firing,
		arg.Since,
		arg.LastFiredAt,
	)
	return err
}
