// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert_channels.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createAlertChannel = `-- name: CreateAlertChannel :one
INSERT INTO alert_channels (
  account_id, kind, label, enabled, config_ciphertext, wrapped_dek, key_version
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
RETURNING id
`

type CreateAlertChannelParams struct {
	AccountID        uuid.UUID
	Kind             string
	Label            string
	Enabled          bool
	ConfigCiphertext []byte
	WrappedDek       []byte
	KeyVersion       int32
}

func (q *Queries) CreateAlertChannel(ctx context.Context, arg CreateAlertChannelParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAlertChannel,
		arg.AccountID,
		arg.Kind,
		arg.Label,
		arg.Enabled,
		arg.ConfigCiphertext,
		arg.WrappedDek,
		arg.KeyVersion,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAlertChannel = `-- name: DeleteAlertChannel :execrows
DELETE FROM alert_channels
WHERE account_id = $1 AND id = $2
`

type DeleteAlertChannelParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteAlertChannel(ctx context.Context, arg DeleteAlertChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlertChannel, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAlertChannels = `-- name: ListAlertChannels :many
SELECT id, kind, label, enabled, config_ciphertext, wrapped_dek, key_version, created_at
FROM alert_channels
WHERE account_id = $1
ORDER BY label
`

type ListAlertChannelsRow struct {
	ID               uuid.UUID
	Kind             string
	Label            string
	Enabled          bool
	ConfigCiphertext []byte
	WrappedDek       []byte
	KeyVersion       int32
	CreatedAt        time.Time
}

// The sealed config comes back with the row: every caller that lists channels is about to
// send through them, and a second query to fetch the secret would be a second place to get
// the account scoping wrong.
func (q *Queries) ListAlertChannels(ctx context.Context, accountID uuid.UUID) ([]ListAlertChannelsRow, error) {
	rows, err := q.db.Query(ctx, listAlertChannels, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertChannelsRow{}
	for rows.Next() {
		var i ListAlertChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Label,
			&i.Enabled,
			&i.ConfigCiphertext,
			&i.WrappedDek,
			&i.KeyVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
