// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset.sql

package store

import (
	"context"
	"time"
)

const resolveAssetAlias = `-- name: ResolveAssetAlias :one
SELECT asset_id
FROM asset_aliases
WHERE source = $1
  AND external_symbol = $2
  AND validity @> $3::timestamptz
`

type ResolveAssetAliasParams struct {
	Source         string
	ExternalSymbol string
	At             time.Time
}

// K22/L8: resolution happens at the event's own time, never with today's mapping. The
// exclusion constraint guarantees at most one row matches, so :one is exact rather than
// a truncation of several candidates.
func (q *Queries) ResolveAssetAlias(ctx context.Context, arg ResolveAssetAliasParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveAssetAlias, arg.Source, arg.ExternalSymbol, arg.At)
	var asset_id int64
	err := row.Scan(&asset_id)
	return asset_id, err
}
