// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset.sql

package store

import (
	"context"
	"time"
)

const getAssetSymbol = `-- name: GetAssetSymbol :one
SELECT canonical_symbol FROM assets WHERE id = $1
`

// The canonical name of an asset id. Reconciliation compares by canonical symbol, and this is
// how it gets there from the id an alias resolved to (L8).
func (q *Queries) GetAssetSymbol(ctx context.Context, assetID int64) (string, error) {
	row := q.db.QueryRow(ctx, getAssetSymbol, assetID)
	var canonical_symbol string
	err := row.Scan(&canonical_symbol)
	return canonical_symbol, err
}

const resolveAssetAlias = `-- name: ResolveAssetAlias :one
SELECT asset_id
FROM asset_aliases
WHERE source = $1
  AND external_symbol = $2
  AND validity @> $3::timestamptz
`

type ResolveAssetAliasParams struct {
	Source         string
	ExternalSymbol string
	At             time.Time
}

// K22/L8: resolution happens at the event's own time, never with today's mapping. The
// exclusion constraint guarantees at most one row matches, so :one is exact rather than
// a truncation of several candidates.
func (q *Queries) ResolveAssetAlias(ctx context.Context, arg ResolveAssetAliasParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveAssetAlias, arg.Source, arg.ExternalSymbol, arg.At)
	var asset_id int64
	err := row.Scan(&asset_id)
	return asset_id, err
}
