// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const consumeInvite = `-- name: ConsumeInvite :one
SELECT auth_consume_invite(
  $1, $2, $3, $4
) AS account_id
`

type ConsumeInviteParams struct {
	TokenHash    []byte
	Email        string
	PasswordHash string
	Now          time.Time
}

func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeInvite,
		arg.TokenHash,
		arg.Email,
		arg.PasswordHash,
		arg.Now,
	)
	var account_id uuid.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (token_hash, email, expires_at)
VALUES ($1, $2, $3)
`

type CreateInviteParams struct {
	TokenHash []byte
	Email     string
	ExpiresAt time.Time
}

// Reached only by plimsollctl, which connects as plimsoll_owner. The app role holds no
// grant on invites, so this statement is unusable from the request path.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite, arg.TokenHash, arg.Email, arg.ExpiresAt)
	return err
}

const createSession = `-- name: CreateSession :exec
SELECT auth_create_session(
  $1, $2, $3
)
`

type CreateSessionParams struct {
	AccountID uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
SELECT auth_delete_session($1, $2)
`

type DeleteSessionParams struct {
	AccountID uuid.UUID
	TokenHash []byte
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.AccountID, arg.TokenHash)
	return err
}

const lookupCredentials = `-- name: LookupCredentials :one

SELECT email, account_id, password_hash, updated_at FROM auth_lookup_credentials($1)
`

// The pre-authentication surface. Every query here goes through a SECURITY DEFINER
// function because it runs before an account context exists and therefore cannot go
// through tenancy.InTx. See migration 00003 for why that is, and for what each function
// is allowed to see.
// The function returns SETOF account_credentials, so sqlc types this row from the table
// definition. Returns no rows for an unknown email, which the caller sees as
// pgx.ErrNoRows and must not distinguish from a wrong password.
func (q *Queries) LookupCredentials(ctx context.Context, email string) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, lookupCredentials, email)
	var i AccountCredential
	err := row.Scan(
		&i.Email,
		&i.AccountID,
		&i.PasswordHash,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveSession = `-- name: ResolveSession :one
SELECT auth_resolve_session(
  $1, $2, $3
) AS account_id
`

type ResolveSessionParams struct {
	AccountID uuid.UUID
	TokenHash []byte
	Now       time.Time
}

func (q *Queries) ResolveSession(ctx context.Context, arg ResolveSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveSession, arg.AccountID, arg.TokenHash, arg.Now)
	var account_id uuid.UUID
	err := row.Scan(&account_id)
	return account_id, err
}
