// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backfill.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getBackfillProgress = `-- name: GetBackfillProgress :one
SELECT scope, cursor, completed_at
FROM backfill_progress
WHERE account_id = $1
  AND integration_id = $2
  AND scope = $3
`

type GetBackfillProgressParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	Scope         string
}

type GetBackfillProgressRow struct {
	Scope       string
	Cursor      string
	CompletedAt *time.Time
}

// Scoped by account_id as the primary defence (L12); RLS is the backstop underneath it.
func (q *Queries) GetBackfillProgress(ctx context.Context, arg GetBackfillProgressParams) (GetBackfillProgressRow, error) {
	row := q.db.QueryRow(ctx, getBackfillProgress, arg.AccountID, arg.IntegrationID, arg.Scope)
	var i GetBackfillProgressRow
	err := row.Scan(&i.Scope, &i.Cursor, &i.CompletedAt)
	return i, err
}

const listBackfillProgress = `-- name: ListBackfillProgress :many
SELECT scope, cursor, completed_at
FROM backfill_progress
WHERE account_id = $1
  AND integration_id = $2
  AND scope LIKE $3
ORDER BY scope
`

type ListBackfillProgressParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	ScopePrefix   string
}

type ListBackfillProgressRow struct {
	Scope       string
	Cursor      string
	CompletedAt *time.Time
}

// Ordered by scope so that a caller resuming a sweep sees them in the same order twice.
func (q *Queries) ListBackfillProgress(ctx context.Context, arg ListBackfillProgressParams) ([]ListBackfillProgressRow, error) {
	rows, err := q.db.Query(ctx, listBackfillProgress, arg.AccountID, arg.IntegrationID, arg.ScopePrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackfillProgressRow{}
	for rows.Next() {
		var i ListBackfillProgressRow
		if err := rows.Scan(&i.Scope, &i.Cursor, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openBackfillScope = `-- name: OpenBackfillScope :exec
INSERT INTO backfill_progress (account_id, integration_id, scope)
VALUES ($1, $2, $3)
ON CONFLICT (integration_id, scope) DO NOTHING
`

type OpenBackfillScopeParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	Scope         string
}

// Records that a scope has work to do without disturbing one already underway. Discovery
// uses it to hand each traded symbol to the trade walk; a rerun must not rewind a walk
// that has since made progress, so the conflict does nothing rather than resetting.
func (q *Queries) OpenBackfillScope(ctx context.Context, arg OpenBackfillScopeParams) error {
	_, err := q.db.Exec(ctx, openBackfillScope, arg.AccountID, arg.IntegrationID, arg.Scope)
	return err
}

const reopenBackfillScopes = `-- name: ReopenBackfillScopes :execrows
UPDATE backfill_progress
   SET cursor = '', completed_at = NULL, updated_at = now()
 WHERE account_id = $1
   AND integration_id = $2
`

type ReopenBackfillScopesParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

// Rewinds every scope of one integration so the history walk runs again (K55).
//
// This is the whole of "resync". It writes no correction and touches no ledger row (L2):
// anything genuinely missing is appended by the ordinary ingest path under the ordinary dedup
// key, and anything already present is deduplicated away (L5) -- which is what makes rewinding
// to the beginning safe rather than reckless.
//
// The cursor goes to ” and not to NULL: the column is NOT NULL precisely so that "nothing
// walked yet" has one spelling rather than two (migration 00013).
func (q *Queries) ReopenBackfillScopes(ctx context.Context, arg ReopenBackfillScopesParams) (int64, error) {
	result, err := q.db.Exec(ctx, reopenBackfillScopes, arg.AccountID, arg.IntegrationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertBackfillProgress = `-- name: UpsertBackfillProgress :exec
INSERT INTO backfill_progress (
  account_id, integration_id, scope, cursor, completed_at
) VALUES (
  $1, $2, $3,
  $4, $5
)
ON CONFLICT (integration_id, scope) DO UPDATE SET
  cursor       = EXCLUDED.cursor,
  completed_at = EXCLUDED.completed_at,
  updated_at   = now()
`

type UpsertBackfillProgressParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	Scope         string
	Cursor        string
	CompletedAt   *time.Time
}

// The write a walker makes in the same transaction as the events the cursor describes.
func (q *Queries) UpsertBackfillProgress(ctx context.Context, arg UpsertBackfillProgressParams) error {
	_, err := q.db.Exec(ctx, upsertBackfillProgress,
		arg.AccountID,
		arg.IntegrationID,
		arg.Scope,
		arg.Cursor,
		arg.CompletedAt,
	)
	return err
}
