// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const dropAssetBalances = `-- name: DropAssetBalances :exec
DELETE FROM asset_balances
WHERE account_id = $1 AND integration_id = $2
`

type DropAssetBalancesParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

func (q *Queries) DropAssetBalances(ctx context.Context, arg DropAssetBalancesParams) error {
	_, err := q.db.Exec(ctx, dropAssetBalances, arg.AccountID, arg.IntegrationID)
	return err
}

const getInstrumentLegs = `-- name: GetInstrumentLegs :one
SELECT base_asset_id, quote_asset_id FROM instruments WHERE id = $1
`

type GetInstrumentLegsRow struct {
	BaseAssetID  int64
	QuoteAssetID int64
}

// The two assets an instrument is made of. Read by id rather than by symbol: the event
// already carries the instrument the alias resolved to at its own event_time (L8), and
// going back through the symbol here would re-ask a question already answered correctly.
func (q *Queries) GetInstrumentLegs(ctx context.Context, instrumentID int64) (GetInstrumentLegsRow, error) {
	row := q.db.QueryRow(ctx, getInstrumentLegs, instrumentID)
	var i GetInstrumentLegsRow
	err := row.Scan(&i.BaseAssetID, &i.QuoteAssetID)
	return i, err
}

const listAccountBalances = `-- name: ListAccountBalances :many
SELECT b.integration_id, b.asset_id, a.canonical_symbol, b.quantity, b.last_event_time
FROM asset_balances b
JOIN assets a ON a.id = b.asset_id
WHERE b.account_id = $1
ORDER BY a.canonical_symbol, b.integration_id
`

type ListAccountBalancesRow struct {
	IntegrationID   uuid.UUID
	AssetID         int64
	CanonicalSymbol string
	Quantity        decimal.Decimal
	LastEventTime   time.Time
}

// Every balance the account holds, across every integration, with the ticker a reader
// recognises rather than an id only the schema knows.
func (q *Queries) ListAccountBalances(ctx context.Context, accountID uuid.UUID) ([]ListAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, listAccountBalances, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountBalancesRow{}
	for rows.Next() {
		var i ListAccountBalancesRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.AssetID,
			&i.CanonicalSymbol,
			&i.Quantity,
			&i.LastEventTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetBalances = `-- name: ListAssetBalances :many
SELECT asset_id, quantity, last_event_time, last_venue_sequence, last_venue_event_id
FROM asset_balances
WHERE account_id = $1 AND integration_id = $2
ORDER BY asset_id
`

type ListAssetBalancesParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

type ListAssetBalancesRow struct {
	AssetID           int64
	Quantity          decimal.Decimal
	LastEventTime     time.Time
	LastVenueSequence int64
	LastVenueEventID  string
}

func (q *Queries) ListAssetBalances(ctx context.Context, arg ListAssetBalancesParams) ([]ListAssetBalancesRow, error) {
	rows, err := q.db.Query(ctx, listAssetBalances, arg.AccountID, arg.IntegrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetBalancesRow{}
	for rows.Next() {
		var i ListAssetBalancesRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Quantity,
			&i.LastEventTime,
			&i.LastVenueSequence,
			&i.LastVenueEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationBalancesWithSymbol = `-- name: ListIntegrationBalancesWithSymbol :many
SELECT b.asset_id, a.canonical_symbol, b.quantity
FROM asset_balances b
JOIN assets a ON a.id = b.asset_id
WHERE b.account_id = $1
  AND b.integration_id = $2
ORDER BY a.canonical_symbol
`

type ListIntegrationBalancesWithSymbolParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

type ListIntegrationBalancesWithSymbolRow struct {
	AssetID         int64
	CanonicalSymbol string
	Quantity        decimal.Decimal
}

// One integration's asset fold, carrying the canonical symbol the venue's code resolves to.
// Reconciliation compares against this: the venue's own code is resolved through the alias
// table at the snapshot's instant and never used as a key itself (L8, K22).
func (q *Queries) ListIntegrationBalancesWithSymbol(ctx context.Context, arg ListIntegrationBalancesWithSymbolParams) ([]ListIntegrationBalancesWithSymbolRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationBalancesWithSymbol, arg.AccountID, arg.IntegrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntegrationBalancesWithSymbolRow{}
	for rows.Next() {
		var i ListIntegrationBalancesWithSymbolRow
		if err := rows.Scan(&i.AssetID, &i.CanonicalSymbol, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsWithUnattributedFees = `-- name: ListIntegrationsWithUnattributedFees :many
SELECT DISTINCT integration_id
FROM ledger_events
WHERE account_id = $1
  AND fee IS NOT NULL AND fee <> 0
  AND fee_asset_id IS NULL
ORDER BY integration_id
`

// Integrations holding a fee whose asset never resolved. The fee was still stored -- losing
// a fill to keep a fee would be the worse trade -- so the balance for that asset is short
// by exactly these amounts, and the reader is told rather than left to discover it during a
// reconciliation (K22, L11).
func (q *Queries) ListIntegrationsWithUnattributedFees(ctx context.Context, accountID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listIntegrationsWithUnattributedFees, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var integration_id uuid.UUID
		if err := rows.Scan(&integration_id); err != nil {
			return nil, err
		}
		items = append(items, integration_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenueIdentitiesSeenTwice = `-- name: ListVenueIdentitiesSeenTwice :many
SELECT venue_event_id, count(DISTINCT integration_id) AS integrations
FROM ledger_events
WHERE account_id = $1
GROUP BY venue_event_id
HAVING count(DISTINCT integration_id) > 1
ORDER BY venue_event_id
`

type ListVenueIdentitiesSeenTwiceRow struct {
	VenueEventID string
	Integrations int64
}

// Venue event ids this account holds under more than one integration.
//
// L5's dedup key is UNIQUE (integration_id, venue_event_id), so one trade cannot enter twice
// through one connection. It CAN enter twice through two -- the same sub-account connected
// under two integrations -- and that is the one way a position doubles without any single
// ingest path being wrong. It is therefore the only duplicate this classifier can prove.
func (q *Queries) ListVenueIdentitiesSeenTwice(ctx context.Context, accountID uuid.UUID) ([]ListVenueIdentitiesSeenTwiceRow, error) {
	rows, err := q.db.Query(ctx, listVenueIdentitiesSeenTwice, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVenueIdentitiesSeenTwiceRow{}
	for rows.Next() {
		var i ListVenueIdentitiesSeenTwiceRow
		if err := rows.Scan(&i.VenueEventID, &i.Integrations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUnattributedFeesByAsset = `-- name: SumUnattributedFeesByAsset :many
SELECT fee_asset, SUM(fee)::numeric(38,18) AS total
FROM ledger_events
WHERE account_id = $1
  AND integration_id = $2
  AND fee IS NOT NULL AND fee <> 0
  AND fee_asset_id IS NULL
  AND fee_asset IS NOT NULL
GROUP BY fee_asset
ORDER BY fee_asset
`

type SumUnattributedFeesByAssetParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

type SumUnattributedFeesByAssetRow struct {
	FeeAsset *string
	Total    decimal.Decimal
}

// How much of each asset left the account as a fee we could not attribute.
//
// The fee was stored with its venue asset code but no asset id, because the code resolved to
// nothing (K22). Our balance for that asset is therefore HIGH by exactly this much -- which
// makes this the one piece of evidence that can classify such a gap as `unsupported` rather
// than as a missing event we cannot account for (K54).
func (q *Queries) SumUnattributedFeesByAsset(ctx context.Context, arg SumUnattributedFeesByAssetParams) ([]SumUnattributedFeesByAssetRow, error) {
	rows, err := q.db.Query(ctx, sumUnattributedFeesByAsset, arg.AccountID, arg.IntegrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumUnattributedFeesByAssetRow{}
	for rows.Next() {
		var i SumUnattributedFeesByAssetRow
		if err := rows.Scan(&i.FeeAsset, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssetBalance = `-- name: UpsertAssetBalance :exec
INSERT INTO asset_balances (
  account_id, integration_id, asset_id, quantity,
  last_event_time, last_venue_sequence, last_venue_event_id
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
ON CONFLICT (integration_id, asset_id) DO UPDATE SET
  quantity            = EXCLUDED.quantity,
  last_event_time     = EXCLUDED.last_event_time,
  last_venue_sequence = EXCLUDED.last_venue_sequence,
  last_venue_event_id = EXCLUDED.last_venue_event_id,
  updated_at          = now()
`

type UpsertAssetBalanceParams struct {
	AccountID         uuid.UUID
	IntegrationID     uuid.UUID
	AssetID           int64
	Quantity          decimal.Decimal
	LastEventTime     time.Time
	LastVenueSequence int64
	LastVenueEventID  string
}

func (q *Queries) UpsertAssetBalance(ctx context.Context, arg UpsertAssetBalanceParams) error {
	_, err := q.db.Exec(ctx, upsertAssetBalance,
		arg.AccountID,
		arg.IntegrationID,
		arg.AssetID,
		arg.Quantity,
		arg.LastEventTime,
		arg.LastVenueSequence,
		arg.LastVenueEventID,
	)
	return err
}
