// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const dropAssetBalances = `-- name: DropAssetBalances :exec
DELETE FROM asset_balances
WHERE account_id = $1 AND integration_id = $2
`

type DropAssetBalancesParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

func (q *Queries) DropAssetBalances(ctx context.Context, arg DropAssetBalancesParams) error {
	_, err := q.db.Exec(ctx, dropAssetBalances, arg.AccountID, arg.IntegrationID)
	return err
}

const getInstrumentLegs = `-- name: GetInstrumentLegs :one
SELECT base_asset_id, quote_asset_id FROM instruments WHERE id = $1
`

type GetInstrumentLegsRow struct {
	BaseAssetID  int64
	QuoteAssetID int64
}

// The two assets an instrument is made of. Read by id rather than by symbol: the event
// already carries the instrument the alias resolved to at its own event_time (L8), and
// going back through the symbol here would re-ask a question already answered correctly.
func (q *Queries) GetInstrumentLegs(ctx context.Context, instrumentID int64) (GetInstrumentLegsRow, error) {
	row := q.db.QueryRow(ctx, getInstrumentLegs, instrumentID)
	var i GetInstrumentLegsRow
	err := row.Scan(&i.BaseAssetID, &i.QuoteAssetID)
	return i, err
}

const listAccountBalances = `-- name: ListAccountBalances :many
SELECT b.integration_id, b.asset_id, a.canonical_symbol, b.quantity, b.last_event_time
FROM asset_balances b
JOIN assets a ON a.id = b.asset_id
WHERE b.account_id = $1
ORDER BY a.canonical_symbol, b.integration_id
`

type ListAccountBalancesRow struct {
	IntegrationID   uuid.UUID
	AssetID         int64
	CanonicalSymbol string
	Quantity        decimal.Decimal
	LastEventTime   time.Time
}

// Every balance the account holds, across every integration, with the ticker a reader
// recognises rather than an id only the schema knows.
func (q *Queries) ListAccountBalances(ctx context.Context, accountID uuid.UUID) ([]ListAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, listAccountBalances, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountBalancesRow{}
	for rows.Next() {
		var i ListAccountBalancesRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.AssetID,
			&i.CanonicalSymbol,
			&i.Quantity,
			&i.LastEventTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetBalances = `-- name: ListAssetBalances :many
SELECT asset_id, quantity, last_event_time, last_venue_sequence, last_venue_event_id
FROM asset_balances
WHERE account_id = $1 AND integration_id = $2
ORDER BY asset_id
`

type ListAssetBalancesParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

type ListAssetBalancesRow struct {
	AssetID           int64
	Quantity          decimal.Decimal
	LastEventTime     time.Time
	LastVenueSequence int64
	LastVenueEventID  string
}

func (q *Queries) ListAssetBalances(ctx context.Context, arg ListAssetBalancesParams) ([]ListAssetBalancesRow, error) {
	rows, err := q.db.Query(ctx, listAssetBalances, arg.AccountID, arg.IntegrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetBalancesRow{}
	for rows.Next() {
		var i ListAssetBalancesRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Quantity,
			&i.LastEventTime,
			&i.LastVenueSequence,
			&i.LastVenueEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsWithUnattributedFees = `-- name: ListIntegrationsWithUnattributedFees :many
SELECT DISTINCT integration_id
FROM ledger_events
WHERE account_id = $1
  AND fee IS NOT NULL AND fee <> 0
  AND fee_asset_id IS NULL
ORDER BY integration_id
`

// Integrations holding a fee whose asset never resolved. The fee was still stored -- losing
// a fill to keep a fee would be the worse trade -- so the balance for that asset is short
// by exactly these amounts, and the reader is told rather than left to discover it during a
// reconciliation (K22, L11).
func (q *Queries) ListIntegrationsWithUnattributedFees(ctx context.Context, accountID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listIntegrationsWithUnattributedFees, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var integration_id uuid.UUID
		if err := rows.Scan(&integration_id); err != nil {
			return nil, err
		}
		items = append(items, integration_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssetBalance = `-- name: UpsertAssetBalance :exec
INSERT INTO asset_balances (
  account_id, integration_id, asset_id, quantity,
  last_event_time, last_venue_sequence, last_venue_event_id
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
ON CONFLICT (integration_id, asset_id) DO UPDATE SET
  quantity            = EXCLUDED.quantity,
  last_event_time     = EXCLUDED.last_event_time,
  last_venue_sequence = EXCLUDED.last_venue_sequence,
  last_venue_event_id = EXCLUDED.last_venue_event_id,
  updated_at          = now()
`

type UpsertAssetBalanceParams struct {
	AccountID         uuid.UUID
	IntegrationID     uuid.UUID
	AssetID           int64
	Quantity          decimal.Decimal
	LastEventTime     time.Time
	LastVenueSequence int64
	LastVenueEventID  string
}

func (q *Queries) UpsertAssetBalance(ctx context.Context, arg UpsertAssetBalanceParams) error {
	_, err := q.db.Exec(ctx, upsertAssetBalance,
		arg.AccountID,
		arg.IntegrationID,
		arg.AssetID,
		arg.Quantity,
		arg.LastEventTime,
		arg.LastVenueSequence,
		arg.LastVenueEventID,
	)
	return err
}
