// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collateral.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const deleteCollateralPositions = `-- name: DeleteCollateralPositions :exec
DELETE FROM collateral_positions
WHERE account_id = $1 AND integration_id = $2
`

type DeleteCollateralPositionsParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

// Cleared before each capture's rows go in, inside one transaction. A position that closed
// between two captures has no row in the new one, and merging instead of replacing would
// leave it on the screen forever -- a closed position still showing a liquidation distance,
// which is the most alarming possible way to be wrong.
func (q *Queries) DeleteCollateralPositions(ctx context.Context, arg DeleteCollateralPositionsParams) error {
	_, err := q.db.Exec(ctx, deleteCollateralPositions, arg.AccountID, arg.IntegrationID)
	return err
}

const getCollateralSnapshot = `-- name: GetCollateralSnapshot :one
SELECT integration_id, as_of, captured_at, margin_balance, wallet_balance,
       unrealized_pnl, maintenance_margin, available_balance
FROM collateral_snapshots
WHERE account_id = $1 AND integration_id = $2
`

type GetCollateralSnapshotParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

type GetCollateralSnapshotRow struct {
	IntegrationID     uuid.UUID
	AsOf              time.Time
	CapturedAt        time.Time
	MarginBalance     decimal.Decimal
	WalletBalance     decimal.Decimal
	UnrealizedPnl     decimal.Decimal
	MaintenanceMargin decimal.Decimal
	AvailableBalance  decimal.Decimal
}

// account_id is the primary defence (L12); RLS is the backstop underneath it.
func (q *Queries) GetCollateralSnapshot(ctx context.Context, arg GetCollateralSnapshotParams) (GetCollateralSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getCollateralSnapshot, arg.AccountID, arg.IntegrationID)
	var i GetCollateralSnapshotRow
	err := row.Scan(
		&i.IntegrationID,
		&i.AsOf,
		&i.CapturedAt,
		&i.MarginBalance,
		&i.WalletBalance,
		&i.UnrealizedPnl,
		&i.MaintenanceMargin,
		&i.AvailableBalance,
	)
	return i, err
}

const insertCollateralPosition = `-- name: InsertCollateralPosition :exec
INSERT INTO collateral_positions (
  account_id, integration_id, instrument_id,
  quantity, entry_price, mark_price, liquidation_price, notional, leverage, maint_margin
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9, $10
)
`

type InsertCollateralPositionParams struct {
	AccountID        uuid.UUID
	IntegrationID    uuid.UUID
	InstrumentID     int64
	Quantity         decimal.Decimal
	EntryPrice       decimal.Decimal
	MarkPrice        decimal.Decimal
	LiquidationPrice decimal.Decimal
	Notional         decimal.Decimal
	Leverage         decimal.Decimal
	MaintMargin      decimal.Decimal
}

func (q *Queries) InsertCollateralPosition(ctx context.Context, arg InsertCollateralPositionParams) error {
	_, err := q.db.Exec(ctx, insertCollateralPosition,
		arg.AccountID,
		arg.IntegrationID,
		arg.InstrumentID,
		arg.Quantity,
		arg.EntryPrice,
		arg.MarkPrice,
		arg.LiquidationPrice,
		arg.Notional,
		arg.Leverage,
		arg.MaintMargin,
	)
	return err
}

const listAccountCollateral = `-- name: ListAccountCollateral :many
SELECT s.integration_id, s.as_of, s.captured_at, s.margin_balance, s.wallet_balance,
       s.unrealized_pnl, s.maintenance_margin, s.available_balance
FROM collateral_snapshots s
WHERE s.account_id = $1
ORDER BY s.integration_id
`

type ListAccountCollateralRow struct {
	IntegrationID     uuid.UUID
	AsOf              time.Time
	CapturedAt        time.Time
	MarginBalance     decimal.Decimal
	WalletBalance     decimal.Decimal
	UnrealizedPnl     decimal.Decimal
	MaintenanceMargin decimal.Decimal
	AvailableBalance  decimal.Decimal
}

// Every integration's snapshot for one account, so a risk response is one read rather than
// one per connection.
func (q *Queries) ListAccountCollateral(ctx context.Context, accountID uuid.UUID) ([]ListAccountCollateralRow, error) {
	rows, err := q.db.Query(ctx, listAccountCollateral, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountCollateralRow{}
	for rows.Next() {
		var i ListAccountCollateralRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.AsOf,
			&i.CapturedAt,
			&i.MarginBalance,
			&i.WalletBalance,
			&i.UnrealizedPnl,
			&i.MaintenanceMargin,
			&i.AvailableBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollateralPositions = `-- name: ListCollateralPositions :many
SELECT p.integration_id, p.instrument_id, i.canonical_symbol,
       p.quantity, p.entry_price, p.mark_price, p.liquidation_price,
       p.notional, p.leverage, p.maint_margin
FROM collateral_positions p
JOIN instruments i ON i.id = p.instrument_id
WHERE p.account_id = $1
ORDER BY p.integration_id, i.canonical_symbol
`

type ListCollateralPositionsRow struct {
	IntegrationID    uuid.UUID
	InstrumentID     int64
	CanonicalSymbol  string
	Quantity         decimal.Decimal
	EntryPrice       decimal.Decimal
	MarkPrice        decimal.Decimal
	LiquidationPrice decimal.Decimal
	Notional         decimal.Decimal
	Leverage         decimal.Decimal
	MaintMargin      decimal.Decimal
}

func (q *Queries) ListCollateralPositions(ctx context.Context, accountID uuid.UUID) ([]ListCollateralPositionsRow, error) {
	rows, err := q.db.Query(ctx, listCollateralPositions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollateralPositionsRow{}
	for rows.Next() {
		var i ListCollateralPositionsRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.InstrumentID,
			&i.CanonicalSymbol,
			&i.Quantity,
			&i.EntryPrice,
			&i.MarkPrice,
			&i.LiquidationPrice,
			&i.Notional,
			&i.Leverage,
			&i.MaintMargin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeverageBrackets = `-- name: ListLeverageBrackets :many
SELECT integration_id, instrument_id, bracket, notional_floor, notional_cap,
       maint_margin_ratio, cum
FROM leverage_brackets
WHERE account_id = $1 AND instrument_id = $2
ORDER BY notional_floor
`

type ListLeverageBracketsParams struct {
	AccountID    uuid.UUID
	InstrumentID int64
}

type ListLeverageBracketsRow struct {
	IntegrationID    uuid.UUID
	InstrumentID     int64
	Bracket          int32
	NotionalFloor    decimal.Decimal
	NotionalCap      decimal.Decimal
	MaintMarginRatio decimal.Decimal
	Cum              decimal.Decimal
}

func (q *Queries) ListLeverageBrackets(ctx context.Context, arg ListLeverageBracketsParams) ([]ListLeverageBracketsRow, error) {
	rows, err := q.db.Query(ctx, listLeverageBrackets, arg.AccountID, arg.InstrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeverageBracketsRow{}
	for rows.Next() {
		var i ListLeverageBracketsRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.InstrumentID,
			&i.Bracket,
			&i.NotionalFloor,
			&i.NotionalCap,
			&i.MaintMarginRatio,
			&i.Cum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCollateralSnapshot = `-- name: UpsertCollateralSnapshot :exec
INSERT INTO collateral_snapshots (
  account_id, integration_id, as_of, captured_at,
  margin_balance, wallet_balance, unrealized_pnl, maintenance_margin, available_balance
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9
)
ON CONFLICT (integration_id) DO UPDATE SET
  as_of              = EXCLUDED.as_of,
  captured_at        = EXCLUDED.captured_at,
  margin_balance     = EXCLUDED.margin_balance,
  wallet_balance     = EXCLUDED.wallet_balance,
  unrealized_pnl     = EXCLUDED.unrealized_pnl,
  maintenance_margin = EXCLUDED.maintenance_margin,
  available_balance  = EXCLUDED.available_balance
`

type UpsertCollateralSnapshotParams struct {
	AccountID         uuid.UUID
	IntegrationID     uuid.UUID
	AsOf              time.Time
	CapturedAt        time.Time
	MarginBalance     decimal.Decimal
	WalletBalance     decimal.Decimal
	UnrealizedPnl     decimal.Decimal
	MaintenanceMargin decimal.Decimal
	AvailableBalance  decimal.Decimal
}

// Latest-only, replaced wholesale. A snapshot is the exchange's answer about one instant and
// there is no arithmetic that combines two of them, so there is nothing to merge: the new
// one is the answer and the old one was.
func (q *Queries) UpsertCollateralSnapshot(ctx context.Context, arg UpsertCollateralSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertCollateralSnapshot,
		arg.AccountID,
		arg.IntegrationID,
		arg.AsOf,
		arg.CapturedAt,
		arg.MarginBalance,
		arg.WalletBalance,
		arg.UnrealizedPnl,
		arg.MaintenanceMargin,
		arg.AvailableBalance,
	)
	return err
}

const upsertLeverageBracket = `-- name: UpsertLeverageBracket :exec
INSERT INTO leverage_brackets (
  account_id, integration_id, instrument_id, bracket,
  notional_floor, notional_cap, maint_margin_ratio, cum, captured_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9
)
ON CONFLICT (integration_id, instrument_id, bracket) DO UPDATE SET
  notional_floor     = EXCLUDED.notional_floor,
  notional_cap       = EXCLUDED.notional_cap,
  maint_margin_ratio = EXCLUDED.maint_margin_ratio,
  cum                = EXCLUDED.cum,
  captured_at        = EXCLUDED.captured_at
`

type UpsertLeverageBracketParams struct {
	AccountID        uuid.UUID
	IntegrationID    uuid.UUID
	InstrumentID     int64
	Bracket          int32
	NotionalFloor    decimal.Decimal
	NotionalCap      decimal.Decimal
	MaintMarginRatio decimal.Decimal
	Cum              decimal.Decimal
	CapturedAt       time.Time
}

// Upserted rather than replaced: the tier table changes rarely and a capture that fetched
// fewer symbols than the last one must not delete the tiers of a position it did not ask
// about. A stale bracket is a number M7.5 can still shock; a missing one is an error it
// cannot answer through.
func (q *Queries) UpsertLeverageBracket(ctx context.Context, arg UpsertLeverageBracketParams) error {
	_, err := q.db.Exec(ctx, upsertLeverageBracket,
		arg.AccountID,
		arg.IntegrationID,
		arg.InstrumentID,
		arg.Bracket,
		arg.NotionalFloor,
		arg.NotionalCap,
		arg.MaintMarginRatio,
		arg.Cum,
		arg.CapturedAt,
	)
	return err
}
