// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"
)

const notifyAccount = `-- name: NotifyAccount :exec
SELECT pg_notify($1, $2)
`

type NotifyAccountParams struct {
	Channel string
	Payload string
}

// The live-update hint (K51). pg_notify rather than the NOTIFY statement because the channel
// name is per account and NOTIFY cannot take a parameter -- and building an identifier by
// string concatenation is how an injection gets written by someone in a hurry.
//
// Delivered on COMMIT, which is the property that makes this correct: a subscriber is never
// told to re-read a change that then rolls back.
func (q *Queries) NotifyAccount(ctx context.Context, arg NotifyAccountParams) error {
	_, err := q.db.Exec(ctx, notifyAccount, arg.Channel, arg.Payload)
	return err
}
