// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const closeUnseenFindings = `-- name: CloseUnseenFindings :exec
UPDATE findings
   SET closed_at = $1
 WHERE account_id     = $2
   AND integration_id = $3
   AND closed_at IS NULL
   AND kind = ANY($4::text[])
   AND NOT (subject = ANY($5::text[]))
`

type CloseUnseenFindingsParams struct {
	ClosedAt      *time.Time
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	Kinds         []string
	Subjects      []string
}

// Closes every open finding this pass owns and did not see.
//
// The kind filter is the scope: a pass may only close what it was looking for, or a quiet
// reconciliation run would clear a negative balance nobody has fixed. sqlc.arg(subjects) is
// this pass's complete subject list; an empty pass closes everything it owns, which is the
// correct reading of "I looked and found nothing".
func (q *Queries) CloseUnseenFindings(ctx context.Context, arg CloseUnseenFindingsParams) error {
	_, err := q.db.Exec(ctx, closeUnseenFindings,
		arg.ClosedAt,
		arg.AccountID,
		arg.IntegrationID,
		arg.Kinds,
		arg.Subjects,
	)
	return err
}

const listFindingHistory = `-- name: ListFindingHistory :many
SELECT id, integration_id, kind, subject, severity, detail, delta, raw,
       opened_at, last_seen_at, closed_at, occurrences
  FROM findings
 WHERE account_id = $1
 ORDER BY opened_at DESC
`

type ListFindingHistoryRow struct {
	ID            uuid.UUID
	IntegrationID uuid.UUID
	Kind          string
	Subject       string
	Severity      string
	Detail        string
	Delta         decimal.NullDecimal
	Raw           []byte
	OpenedAt      time.Time
	LastSeenAt    time.Time
	ClosedAt      *time.Time
	Occurrences   int32
}

// Open and closed alike, newest incident first. This is the evidence K55 requires before
// automatic correction is ever allowed to act on a classification.
func (q *Queries) ListFindingHistory(ctx context.Context, accountID uuid.UUID) ([]ListFindingHistoryRow, error) {
	rows, err := q.db.Query(ctx, listFindingHistory, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFindingHistoryRow{}
	for rows.Next() {
		var i ListFindingHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Kind,
			&i.Subject,
			&i.Severity,
			&i.Detail,
			&i.Delta,
			&i.Raw,
			&i.OpenedAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.Occurrences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenFindings = `-- name: ListOpenFindings :many
SELECT id, integration_id, kind, subject, severity, detail, delta, raw,
       opened_at, last_seen_at, closed_at, occurrences
  FROM findings
 WHERE account_id = $1 AND closed_at IS NULL
 ORDER BY CASE severity WHEN 'error' THEN 0 WHEN 'warn' THEN 1 ELSE 2 END, opened_at
`

type ListOpenFindingsRow struct {
	ID            uuid.UUID
	IntegrationID uuid.UUID
	Kind          string
	Subject       string
	Severity      string
	Detail        string
	Delta         decimal.NullDecimal
	Raw           []byte
	OpenedAt      time.Time
	LastSeenAt    time.Time
	ClosedAt      *time.Time
	Occurrences   int32
}

// What is wrong right now: worst first, then oldest first, because a problem that has been
// true for a week is more interesting than one that started a minute ago.
func (q *Queries) ListOpenFindings(ctx context.Context, accountID uuid.UUID) ([]ListOpenFindingsRow, error) {
	rows, err := q.db.Query(ctx, listOpenFindings, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenFindingsRow{}
	for rows.Next() {
		var i ListOpenFindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Kind,
			&i.Subject,
			&i.Severity,
			&i.Detail,
			&i.Delta,
			&i.Raw,
			&i.OpenedAt,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.Occurrences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFinding = `-- name: UpsertFinding :exec
INSERT INTO findings (
  account_id, integration_id, kind, subject, severity, detail, delta, raw,
  opened_at, last_seen_at, occurrences
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9, 1)
ON CONFLICT (account_id, integration_id, kind, subject) WHERE closed_at IS NULL
DO UPDATE SET
  last_seen_at = EXCLUDED.last_seen_at,
  occurrences  = findings.occurrences + 1,
  severity     = EXCLUDED.severity,
  detail       = EXCLUDED.detail,
  delta        = EXCLUDED.delta,
  raw          = EXCLUDED.raw
`

type UpsertFindingParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	Kind          string
	Subject       string
	Severity      string
	Detail        string
	Delta         decimal.NullDecimal
	Raw           []byte
	OpenedAt      time.Time
}

// Opens a finding, or touches the one already open for this subject.
//
// The conflict target is the partial unique index, which covers open rows only -- so a
// problem that returns after closing does not collide with its closed predecessor and starts
// a new incident instead (K53). opened_at is deliberately NOT updated: it is when the problem
// started, and moving it would erase how long it has been true.
func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) error {
	_, err := q.db.Exec(ctx, upsertFinding,
		arg.AccountID,
		arg.IntegrationID,
		arg.Kind,
		arg.Subject,
		arg.Severity,
		arg.Detail,
		arg.Delta,
		arg.Raw,
		arg.OpenedAt,
	)
	return err
}
