// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: funding.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const sumFundingBySymbol = `-- name: SumFundingBySymbol :many
SELECT e.integration_id,
       e.instrument_id,
       i.canonical_symbol,
       a.canonical_symbol AS asset,
       SUM(e.quantity)::numeric(38,18) AS total,
       COUNT(*)::bigint                AS events,
       MIN(e.event_time)::timestamptz  AS first_event_time,
       MAX(e.event_time)::timestamptz  AS last_event_time
FROM ledger_events e
JOIN instruments i ON i.id = e.instrument_id
JOIN assets a      ON a.id = i.quote_asset_id
WHERE e.account_id = $1
  AND e.event_type = 'FUNDING_PAYMENT'
  AND e.event_time >= $2
  AND e.event_time <  $3
GROUP BY e.integration_id, e.instrument_id, i.canonical_symbol, a.canonical_symbol
ORDER BY i.canonical_symbol, e.integration_id
`

type SumFundingBySymbolParams struct {
	AccountID uuid.UUID
	FromTime  time.Time
	ToTime    time.Time
}

type SumFundingBySymbolRow struct {
	IntegrationID   uuid.UUID
	InstrumentID    *int64
	CanonicalSymbol string
	Asset           string
	Total           decimal.Decimal
	Events          int64
	FirstEventTime  time.Time
	LastEventTime   time.Time
}

// What funding cost or paid, per instrument, over a half-open window [from, to).
//
// Summed in the database rather than folded in Go because there is no state to carry: this
// is arithmetic over rows the ledger already holds, and streaming a year of payments through
// the API process to add them up would make the endpoint's cost a property of how long the
// account has been trading.
//
// The asset is the instrument's QUOTE asset, which is what the balance fold credits a
// funding payment to (balance.Deltas). V1 is USD-M only, where the settle asset and the
// quote asset are the same one; taking settle_asset_id here instead would be correct in
// isolation and would silently disagree with the fold the day coin-M arrives.
func (q *Queries) SumFundingBySymbol(ctx context.Context, arg SumFundingBySymbolParams) ([]SumFundingBySymbolRow, error) {
	rows, err := q.db.Query(ctx, sumFundingBySymbol, arg.AccountID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumFundingBySymbolRow{}
	for rows.Next() {
		var i SumFundingBySymbolRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.InstrumentID,
			&i.CanonicalSymbol,
			&i.Asset,
			&i.Total,
			&i.Events,
			&i.FirstEventTime,
			&i.LastEventTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
