// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instrument.sql

package store

import (
	"context"
	"time"
)

const resolveInstrumentAlias = `-- name: ResolveInstrumentAlias :one
SELECT instrument_id
FROM instrument_aliases
WHERE exchange = $1
  AND market = $2
  AND exchange_symbol = $3
  AND validity @> $4::timestamptz
`

type ResolveInstrumentAliasParams struct {
	Exchange       string
	Market         string
	ExchangeSymbol string
	At             time.Time
}

// Market is part of the lookup, not a filter applied afterwards (K10). The exclusion
// constraint guarantees at most one row matches, so :one is exact.
func (q *Queries) ResolveInstrumentAlias(ctx context.Context, arg ResolveInstrumentAliasParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveInstrumentAlias,
		arg.Exchange,
		arg.Market,
		arg.ExchangeSymbol,
		arg.At,
	)
	var instrument_id int64
	err := row.Scan(&instrument_id)
	return instrument_id, err
}
