// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getIntegrationCredential = `-- name: GetIntegrationCredential :one
SELECT credential_ciphertext, wrapped_dek, key_version, credential_verified_at
FROM integrations
WHERE account_id = $1
  AND id = $2
`

type GetIntegrationCredentialParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

type GetIntegrationCredentialRow struct {
	CredentialCiphertext []byte
	WrappedDek           []byte
	KeyVersion           *int32
	CredentialVerifiedAt *time.Time
}

func (q *Queries) GetIntegrationCredential(ctx context.Context, arg GetIntegrationCredentialParams) (GetIntegrationCredentialRow, error) {
	row := q.db.QueryRow(ctx, getIntegrationCredential, arg.AccountID, arg.IntegrationID)
	var i GetIntegrationCredentialRow
	err := row.Scan(
		&i.CredentialCiphertext,
		&i.WrappedDek,
		&i.KeyVersion,
		&i.CredentialVerifiedAt,
	)
	return i, err
}

const setIntegrationCredential = `-- name: SetIntegrationCredential :execrows
UPDATE integrations
SET credential_ciphertext = $1,
    wrapped_dek           = $2,
    key_version           = $3
WHERE account_id = $4
  AND id = $5
`

type SetIntegrationCredentialParams struct {
	CredentialCiphertext []byte
	WrappedDek           []byte
	KeyVersion           *int32
	AccountID            uuid.UUID
	IntegrationID        uuid.UUID
}

// account_id is the application-level scope (L12); RLS is the backstop underneath it. The
// row count is the caller's evidence that the integration exists and belongs to this
// account -- an UPDATE that matches nothing is otherwise indistinguishable from success.
func (q *Queries) SetIntegrationCredential(ctx context.Context, arg SetIntegrationCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIntegrationCredential,
		arg.CredentialCiphertext,
		arg.WrappedDek,
		arg.KeyVersion,
		arg.AccountID,
		arg.IntegrationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
