// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lease.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const claimIntegrationLease = `-- name: ClaimIntegrationLease :one
INSERT INTO integration_leases (
  account_id, integration_id, owner_id, acquired_at, expires_at
) VALUES (
  $1, $2, $3,
  now(), now() + make_interval(secs => $4::int)
)
ON CONFLICT (integration_id) DO UPDATE SET
  owner_id    = EXCLUDED.owner_id,
  acquired_at = EXCLUDED.acquired_at,
  expires_at  = EXCLUDED.expires_at
WHERE integration_leases.expires_at < now()
   OR integration_leases.owner_id = EXCLUDED.owner_id
RETURNING owner_id, expires_at
`

type ClaimIntegrationLeaseParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	OwnerID       string
	TtlSeconds    int32
}

type ClaimIntegrationLeaseRow struct {
	OwnerID   string
	ExpiresAt time.Time
}

// The whole value of this statement is that it is one statement. A read-then-write would
// let two workers both observe an expired lease and both take it; ON CONFLICT DO UPDATE
// takes a row lock, so the loser re-evaluates its WHERE against the winner's committed row
// and comes back with no rows at all (K20).
//
// now() throughout: the database's clock decides, never the worker's. Two workers with
// skewed clocks would otherwise disagree about whether the lease had expired.
//
// Returning no row means "not claimed", which is a normal outcome and not an error.
//
// ttl_seconds is an integer, not a double. sqlc maps a double precision parameter to Go's
// 64-bit floating point type, and internal/store keeps a test that refuses that type
// anywhere in generated code rather than arguing case by case about which values are money
// (L1). A lease measured in whole seconds loses nothing by obeying it.
func (q *Queries) ClaimIntegrationLease(ctx context.Context, arg ClaimIntegrationLeaseParams) (ClaimIntegrationLeaseRow, error) {
	row := q.db.QueryRow(ctx, claimIntegrationLease,
		arg.AccountID,
		arg.IntegrationID,
		arg.OwnerID,
		arg.TtlSeconds,
	)
	var i ClaimIntegrationLeaseRow
	err := row.Scan(&i.OwnerID, &i.ExpiresAt)
	return i, err
}

const heartbeatIntegrationLease = `-- name: HeartbeatIntegrationLease :one
UPDATE integration_leases
SET expires_at = now() + make_interval(secs => $1::int)
WHERE account_id = $2
  AND integration_id = $3
  AND owner_id = $4
  AND expires_at > now()
RETURNING expires_at
`

type HeartbeatIntegrationLeaseParams struct {
	TtlSeconds    int32
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	OwnerID       string
}

// Extends a lease the caller still holds. The expires_at check is not redundant with the
// owner check: a worker that stopped heartbeating long enough for its lease to lapse has
// lost it whether or not anyone else has taken it yet, and letting it resume writing is the
// two-writer race the lease exists to prevent.
func (q *Queries) HeartbeatIntegrationLease(ctx context.Context, arg HeartbeatIntegrationLeaseParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, heartbeatIntegrationLease,
		arg.TtlSeconds,
		arg.AccountID,
		arg.IntegrationID,
		arg.OwnerID,
	)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const leaseIsHeldBy = `-- name: LeaseIsHeldBy :one
SELECT EXISTS (
  SELECT 1 FROM integration_leases
  WHERE account_id = $1
    AND integration_id = $2
    AND owner_id = $3
    AND expires_at > now()
)
`

type LeaseIsHeldByParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	OwnerID       string
}

// Read inside the same transaction as the write it guards. A worker that checked its lease
// and then wrote in a second transaction would have a window between the two for the lease
// to be lost in, and the whole point of a lease is that there is no such window.
func (q *Queries) LeaseIsHeldBy(ctx context.Context, arg LeaseIsHeldByParams) (bool, error) {
	row := q.db.QueryRow(ctx, leaseIsHeldBy, arg.AccountID, arg.IntegrationID, arg.OwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const releaseIntegrationLease = `-- name: ReleaseIntegrationLease :execrows
DELETE FROM integration_leases
WHERE account_id = $1
  AND integration_id = $2
  AND owner_id = $3
`

type ReleaseIntegrationLeaseParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	OwnerID       string
}

// Scoped by owner: a worker may only give up its own lease. Releasing another's would hand
// the integration to a third process while the second was still writing.
func (q *Queries) ReleaseIntegrationLease(ctx context.Context, arg ReleaseIntegrationLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseIntegrationLease, arg.AccountID, arg.IntegrationID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
