// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const insertLedgerEvent = `-- name: InsertLedgerEvent :execrows
INSERT INTO ledger_events (
  account_id, integration_id, venue_event_id, venue_sequence, source, event_type,
  instrument_id, strategy_id, side, quantity, price, fee, fee_asset, event_time, raw
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10, $11, $12, $13,
  $14, $15
)
ON CONFLICT (integration_id, venue_event_id) DO NOTHING
`

type InsertLedgerEventParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	VenueEventID  string
	VenueSequence int64
	Source        string
	EventType     string
	InstrumentID  *int64
	StrategyID    *uuid.UUID
	Side          *string
	Quantity      decimal.NullDecimal
	Price         decimal.NullDecimal
	Fee           decimal.NullDecimal
	FeeAsset      *string
	EventTime     time.Time
	Raw           []byte
}

// ON CONFLICT DO NOTHING is the deduplication mechanism, and it is correct only because
// venue_event_id is built from exchange fields alone (K19, L5). :execrows so the caller
// can report how many of the events it offered were actually new.
func (q *Queries) InsertLedgerEvent(ctx context.Context, arg InsertLedgerEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLedgerEvent,
		arg.AccountID,
		arg.IntegrationID,
		arg.VenueEventID,
		arg.VenueSequence,
		arg.Source,
		arg.EventType,
		arg.InstrumentID,
		arg.StrategyID,
		arg.Side,
		arg.Quantity,
		arg.Price,
		arg.Fee,
		arg.FeeAsset,
		arg.EventTime,
		arg.Raw,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const streamLedgerEvents = `-- name: StreamLedgerEvents :many
SELECT seq, account_id, integration_id, venue_event_id, venue_sequence, source,
       event_type, instrument_id, strategy_id, side, quantity, price, fee, fee_asset,
       event_time, ingested_at, raw
FROM ledger_events
WHERE account_id = $1
  AND integration_id = $2
  AND (event_time, venue_sequence, venue_event_id) >
      ($3::timestamptz,
       $4::bigint,
       $5::text)
ORDER BY event_time, venue_sequence, venue_event_id
LIMIT $6
`

type StreamLedgerEventsParams struct {
	AccountID          uuid.UUID
	IntegrationID      uuid.UUID
	AfterEventTime     time.Time
	AfterVenueSequence int64
	AfterVenueEventID  string
	MaxRows            int32
}

// account_id is the primary defence (L12); RLS is the backstop underneath it. The row
// comparison is the canonical order (L7) used as a keyset cursor -- never the global seq,
// whose values are assigned before commit and can therefore be observed out of order
// (K20, L6).
func (q *Queries) StreamLedgerEvents(ctx context.Context, arg StreamLedgerEventsParams) ([]LedgerEvent, error) {
	rows, err := q.db.Query(ctx, streamLedgerEvents,
		arg.AccountID,
		arg.IntegrationID,
		arg.AfterEventTime,
		arg.AfterVenueSequence,
		arg.AfterVenueEventID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.Seq,
			&i.AccountID,
			&i.IntegrationID,
			&i.VenueEventID,
			&i.VenueSequence,
			&i.Source,
			&i.EventType,
			&i.InstrumentID,
			&i.StrategyID,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.Fee,
			&i.FeeAsset,
			&i.EventTime,
			&i.IngestedAt,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
