// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lineage.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const listPositionEventsAfter = `-- name: ListPositionEventsAfter :many
SELECT seq, venue_event_id, venue_sequence, source, event_type, instrument_id, asset_id,
       strategy_id, side, quantity, price, fee, fee_asset, fee_asset_id,
       event_time, ingested_at, raw
FROM ledger_events
WHERE account_id = $1
  AND integration_id = $2
  AND instrument_id = $3
  AND (event_time, venue_sequence, venue_event_id) >
      ($4::timestamptz,
       $5::bigint,
       $6::text)
ORDER BY event_time, venue_sequence, venue_event_id
LIMIT $7
`

type ListPositionEventsAfterParams struct {
	AccountID          uuid.UUID
	IntegrationID      uuid.UUID
	InstrumentID       *int64
	AfterEventTime     time.Time
	AfterVenueSequence int64
	AfterVenueEventID  string
	MaxRows            int32
}

type ListPositionEventsAfterRow struct {
	Seq           int64
	VenueEventID  string
	VenueSequence int64
	Source        string
	EventType     string
	InstrumentID  *int64
	AssetID       *int64
	StrategyID    *uuid.UUID
	Side          *string
	Quantity      decimal.NullDecimal
	Price         decimal.NullDecimal
	Fee           decimal.NullDecimal
	FeeAsset      *string
	FeeAssetID    *int64
	EventTime     time.Time
	IngestedAt    time.Time
	Raw           []byte
}

// Every event that folds into one position, in canonical order (L7), from a keyset cursor.
//
// Paged rather than fetched whole: the lineage of a five-year position is not bounded by
// anything, and holding all of it in memory to render the last page of it would make the
// endpoint's cost a property of the account's history rather than of the request.
func (q *Queries) ListPositionEventsAfter(ctx context.Context, arg ListPositionEventsAfterParams) ([]ListPositionEventsAfterRow, error) {
	rows, err := q.db.Query(ctx, listPositionEventsAfter,
		arg.AccountID,
		arg.IntegrationID,
		arg.InstrumentID,
		arg.AfterEventTime,
		arg.AfterVenueSequence,
		arg.AfterVenueEventID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionEventsAfterRow{}
	for rows.Next() {
		var i ListPositionEventsAfterRow
		if err := rows.Scan(
			&i.Seq,
			&i.VenueEventID,
			&i.VenueSequence,
			&i.Source,
			&i.EventType,
			&i.InstrumentID,
			&i.AssetID,
			&i.StrategyID,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.Fee,
			&i.FeeAsset,
			&i.FeeAssetID,
			&i.EventTime,
			&i.IngestedAt,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamAccountEvents = `-- name: StreamAccountEvents :many
SELECT e.seq, e.integration_id, e.venue_event_id, e.venue_sequence, e.source, e.event_type,
       e.instrument_id, e.asset_id, e.side, e.quantity, e.price, e.fee, e.fee_asset,
       e.transfer_from, e.transfer_to, e.event_time, e.ingested_at,
       i.canonical_symbol AS instrument_symbol,
       a.canonical_symbol AS asset_symbol
FROM ledger_events e
LEFT JOIN instruments i ON i.id = e.instrument_id
LEFT JOIN assets a ON a.id = e.asset_id
WHERE e.account_id = $1
  AND (e.event_time, e.venue_sequence, e.venue_event_id, e.integration_id) >
      ($2::timestamptz,
       $3::bigint,
       $4::text,
       $5::uuid)
ORDER BY e.event_time, e.venue_sequence, e.venue_event_id, e.integration_id
LIMIT $6
`

type StreamAccountEventsParams struct {
	AccountID          uuid.UUID
	AfterEventTime     time.Time
	AfterVenueSequence int64
	AfterVenueEventID  string
	AfterIntegrationID uuid.UUID
	MaxRows            int32
}

type StreamAccountEventsRow struct {
	Seq              int64
	IntegrationID    uuid.UUID
	VenueEventID     string
	VenueSequence    int64
	Source           string
	EventType        string
	InstrumentID     *int64
	AssetID          *int64
	Side             *string
	Quantity         decimal.NullDecimal
	Price            decimal.NullDecimal
	Fee              decimal.NullDecimal
	FeeAsset         *string
	TransferFrom     *string
	TransferTo       *string
	EventTime        time.Time
	IngestedAt       time.Time
	InstrumentSymbol *string
	AssetSymbol      *string
}

// The account's ledger across every integration, in canonical order with integration_id as
// the last tiebreak -- two integrations can mint the same venue_event_id, and a cursor that
// could not tell them apart would stop at the first of them forever.
//
// Never paginated on seq: identity values are assigned before commit, so a seq cursor can
// skip a row that was still in flight (K20, K41). seq is returned as lineage, not as a
// position in the listing.
func (q *Queries) StreamAccountEvents(ctx context.Context, arg StreamAccountEventsParams) ([]StreamAccountEventsRow, error) {
	rows, err := q.db.Query(ctx, streamAccountEvents,
		arg.AccountID,
		arg.AfterEventTime,
		arg.AfterVenueSequence,
		arg.AfterVenueEventID,
		arg.AfterIntegrationID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreamAccountEventsRow{}
	for rows.Next() {
		var i StreamAccountEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.IntegrationID,
			&i.VenueEventID,
			&i.VenueSequence,
			&i.Source,
			&i.EventType,
			&i.InstrumentID,
			&i.AssetID,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.Fee,
			&i.FeeAsset,
			&i.TransferFrom,
			&i.TransferTo,
			&i.EventTime,
			&i.IngestedAt,
			&i.InstrumentSymbol,
			&i.AssetSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
