// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID         uuid.UUID
	Email      string
	IsAdmin    bool
	CreatedAt  time.Time
	DisabledAt *time.Time
}

type AccountCredential struct {
	Email        string
	AccountID    uuid.UUID
	PasswordHash string
	UpdatedAt    time.Time
}

type Asset struct {
	ID                int64
	CanonicalSymbol   string
	Kind              string
	Chain             *string
	ContractAddress   *string
	IsWrapped         bool
	UnderlyingAssetID *int64
	CreatedAt         time.Time
}

type AssetAlias struct {
	ID             int64
	Source         string
	ExternalSymbol string
	AssetID        int64
	Validity       pgtype.Range[pgtype.Timestamptz]
}

type Instrument struct {
	ID              int64
	CanonicalSymbol string
	Kind            string
	BaseAssetID     int64
	QuoteAssetID    int64
	SettleAssetID   *int64
	ContractSize    decimal.Decimal
	CreatedAt       time.Time
}

type InstrumentAlias struct {
	ID             int64
	Exchange       string
	Market         string
	ExchangeSymbol string
	InstrumentID   int64
	Validity       pgtype.Range[pgtype.Timestamptz]
}

type Invite struct {
	TokenHash  []byte
	Email      string
	CreatedBy  *uuid.UUID
	ConsumedBy *uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

type Session struct {
	TokenHash  []byte
	AccountID  uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
}
