// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolio.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const listAccountFeeAssets = `-- name: ListAccountFeeAssets :many
SELECT DISTINCT a.id, a.canonical_symbol
FROM ledger_events e
JOIN assets a ON a.id = e.fee_asset_id
WHERE e.account_id = $1
  AND e.fee_asset_id IS NOT NULL
ORDER BY a.id
`

type ListAccountFeeAssetsRow struct {
	ID              int64
	CanonicalSymbol string
}

// Every asset this account has ever paid a fee in, as the id the fee was resolved to at
// ingest -- never the venue string the fee arrived as (L8, K22). It is read so the response
// can say fee_price_missing: a fee in an asset the run could not price leaves the fee
// totals honest but unconvertible, and a reader adding them to a USD total would be adding
// a number with no unit.
//
// The unresolved half of the same question is ListIntegrationsWithUnattributedFees, which
// is why this one filters the id to NOT NULL rather than reporting both conditions as one:
// an asset we do not know and an asset we cannot price are different faults with different
// fixes.
func (q *Queries) ListAccountFeeAssets(ctx context.Context, accountID uuid.UUID) ([]ListAccountFeeAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAccountFeeAssets, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountFeeAssetsRow{}
	for rows.Next() {
		var i ListAccountFeeAssetsRow
		if err := rows.Scan(&i.ID, &i.CanonicalSymbol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountPositionFees = `-- name: ListAccountPositionFees :many
SELECT integration_id, instrument_id, fee_asset, amount
FROM position_fees
WHERE account_id = $1
ORDER BY integration_id, instrument_id, fee_asset
`

type ListAccountPositionFeesRow struct {
	IntegrationID uuid.UUID
	InstrumentID  int64
	FeeAsset      string
	Amount        decimal.Decimal
}

func (q *Queries) ListAccountPositionFees(ctx context.Context, accountID uuid.UUID) ([]ListAccountPositionFeesRow, error) {
	rows, err := q.db.Query(ctx, listAccountPositionFees, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountPositionFeesRow{}
	for rows.Next() {
		var i ListAccountPositionFeesRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.InstrumentID,
			&i.FeeAsset,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountPositions = `-- name: ListAccountPositions :many
SELECT p.integration_id, p.instrument_id,
       i.canonical_symbol, i.kind,
       i.base_asset_id, i.quote_asset_id,
       b.canonical_symbol AS base_asset,
       q.canonical_symbol AS quote_asset,
       p.quantity, p.avg_entry_price, p.realized_pnl, p.last_event_time
FROM positions p
JOIN instruments i ON i.id = p.instrument_id
JOIN assets b ON b.id = i.base_asset_id
JOIN assets q ON q.id = i.quote_asset_id
WHERE p.account_id = $1
ORDER BY p.integration_id, p.instrument_id
`

type ListAccountPositionsRow struct {
	IntegrationID   uuid.UUID
	InstrumentID    int64
	CanonicalSymbol string
	Kind            string
	BaseAssetID     int64
	QuoteAssetID    int64
	BaseAsset       string
	QuoteAsset      string
	Quantity        decimal.Decimal
	AvgEntryPrice   decimal.Decimal
	RealizedPnl     decimal.Decimal
	LastEventTime   time.Time
}

// Every folded position the account has, across every integration, joined to the identity
// a reader can recognise. account_id is the primary defence (L12); RLS is the backstop.
//
// The instrument is joined rather than resolved through the alias table: these rows are the
// output of a fold that already resolved each event's symbol as of its own event_time
// (L8, K22), so re-resolving here would be asking today's mapping a question that was
// already answered correctly.
func (q *Queries) ListAccountPositions(ctx context.Context, accountID uuid.UUID) ([]ListAccountPositionsRow, error) {
	rows, err := q.db.Query(ctx, listAccountPositions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountPositionsRow{}
	for rows.Next() {
		var i ListAccountPositionsRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.InstrumentID,
			&i.CanonicalSymbol,
			&i.Kind,
			&i.BaseAssetID,
			&i.QuoteAssetID,
			&i.BaseAsset,
			&i.QuoteAsset,
			&i.Quantity,
			&i.AvgEntryPrice,
			&i.RealizedPnl,
			&i.LastEventTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLaggingIntegrations = `-- name: ListLaggingIntegrations :many
SELECT i.id AS integration_id
FROM integrations i
WHERE i.account_id = $1
  AND EXISTS (
    SELECT 1
    FROM ledger_events e
    LEFT JOIN projection_cursors c
      ON c.account_id = e.account_id AND c.integration_id = e.integration_id
    WHERE e.account_id = i.account_id
      AND e.integration_id = i.id
      AND (c.integration_id IS NULL
           OR (e.event_time, e.venue_sequence, e.venue_event_id) >
              (c.last_event_time, c.last_venue_sequence, c.last_venue_event_id))
  )
ORDER BY i.id
`

// Integrations holding at least one event the fold has not reached.
//
// An EXISTS over the canonical order rather than a count: the question is "is there
// anything after the cursor", which is an index seek, and it stays cheap on a ledger of any
// size. Events that arrived *behind* the cursor are a different failure and are detected by
// the projector itself, by row count (issue #4, K20).
//
// No cursor row at all with events present is lagging by definition: nothing has been
// folded yet.
func (q *Queries) ListLaggingIntegrations(ctx context.Context, accountID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLaggingIntegrations, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var integration_id uuid.UUID
		if err := rows.Scan(&integration_id); err != nil {
			return nil, err
		}
		items = append(items, integration_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
