// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: position.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countLedgerEventsThrough = `-- name: CountLedgerEventsThrough :one
SELECT count(*) FROM ledger_events
WHERE account_id = $1
  AND integration_id = $2
  AND (event_time, venue_sequence, venue_event_id) <=
      ($3::timestamptz,
       $4::bigint,
       $5::text)
`

type CountLedgerEventsThroughParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	EventTime     time.Time
	VenueSequence int64
	VenueEventID  string
}

// How many events sit at or below a cursor, in canonical order. Compared against what the
// projector folded, this detects an event that arrived behind the cursor (issue #4).
func (q *Queries) CountLedgerEventsThrough(ctx context.Context, arg CountLedgerEventsThroughParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerEventsThrough,
		arg.AccountID,
		arg.IntegrationID,
		arg.EventTime,
		arg.VenueSequence,
		arg.VenueEventID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePositionFees = `-- name: DeletePositionFees :exec
DELETE FROM position_fees
WHERE account_id = $1
  AND integration_id = $2
  AND instrument_id = $3
`

type DeletePositionFeesParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	InstrumentID  int64
}

func (q *Queries) DeletePositionFees(ctx context.Context, arg DeletePositionFeesParams) error {
	_, err := q.db.Exec(ctx, deletePositionFees, arg.AccountID, arg.IntegrationID, arg.InstrumentID)
	return err
}

const dropProjection = `-- name: DropProjection :exec
DELETE FROM positions
WHERE account_id = $1 AND integration_id = $2
`

type DropProjectionParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

// The projection only. position_fees cascades from positions, and position_strategies is
// deliberately absent: the tag is user input and survives a rebuild (D2).
func (q *Queries) DropProjection(ctx context.Context, arg DropProjectionParams) error {
	_, err := q.db.Exec(ctx, dropProjection, arg.AccountID, arg.IntegrationID)
	return err
}

const dropProjectionCursor = `-- name: DropProjectionCursor :exec
DELETE FROM projection_cursors
WHERE account_id = $1 AND integration_id = $2
`

type DropProjectionCursorParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

func (q *Queries) DropProjectionCursor(ctx context.Context, arg DropProjectionCursorParams) error {
	_, err := q.db.Exec(ctx, dropProjectionCursor, arg.AccountID, arg.IntegrationID)
	return err
}

const getProjectionCursor = `-- name: GetProjectionCursor :one
SELECT last_event_time, last_venue_sequence, last_venue_event_id, projected_count
FROM projection_cursors
WHERE account_id = $1 AND integration_id = $2
`

type GetProjectionCursorParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

type GetProjectionCursorRow struct {
	LastEventTime     time.Time
	LastVenueSequence int64
	LastVenueEventID  string
	ProjectedCount    int64
}

func (q *Queries) GetProjectionCursor(ctx context.Context, arg GetProjectionCursorParams) (GetProjectionCursorRow, error) {
	row := q.db.QueryRow(ctx, getProjectionCursor, arg.AccountID, arg.IntegrationID)
	var i GetProjectionCursorRow
	err := row.Scan(
		&i.LastEventTime,
		&i.LastVenueSequence,
		&i.LastVenueEventID,
		&i.ProjectedCount,
	)
	return i, err
}

const insertPositionFee = `-- name: InsertPositionFee :exec
INSERT INTO position_fees (account_id, integration_id, instrument_id, fee_asset, amount)
VALUES ($1, $2, $3,
        $4, $5)
`

type InsertPositionFeeParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	InstrumentID  int64
	FeeAsset      string
	Amount        decimal.Decimal
}

func (q *Queries) InsertPositionFee(ctx context.Context, arg InsertPositionFeeParams) error {
	_, err := q.db.Exec(ctx, insertPositionFee,
		arg.AccountID,
		arg.IntegrationID,
		arg.InstrumentID,
		arg.FeeAsset,
		arg.Amount,
	)
	return err
}

const integrationExists = `-- name: IntegrationExists :one
SELECT EXISTS (
  SELECT 1 FROM integrations
  WHERE account_id = $1 AND id = $2
)
`

type IntegrationExistsParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

// The projector names an integration; RLS makes another account's return zero rows rather
// than an error, so without this the fold succeeds having silently done nothing.
func (q *Queries) IntegrationExists(ctx context.Context, arg IntegrationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationExists, arg.AccountID, arg.IntegrationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listPositionFees = `-- name: ListPositionFees :many
SELECT instrument_id, fee_asset, amount
FROM position_fees
WHERE account_id = $1 AND integration_id = $2
ORDER BY instrument_id, fee_asset
`

type ListPositionFeesParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

type ListPositionFeesRow struct {
	InstrumentID int64
	FeeAsset     string
	Amount       decimal.Decimal
}

func (q *Queries) ListPositionFees(ctx context.Context, arg ListPositionFeesParams) ([]ListPositionFeesRow, error) {
	rows, err := q.db.Query(ctx, listPositionFees, arg.AccountID, arg.IntegrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionFeesRow{}
	for rows.Next() {
		var i ListPositionFeesRow
		if err := rows.Scan(&i.InstrumentID, &i.FeeAsset, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT instrument_id, quantity, avg_entry_price, realized_pnl,
       last_event_time, last_venue_sequence, last_venue_event_id
FROM positions
WHERE account_id = $1 AND integration_id = $2
ORDER BY instrument_id
`

type ListPositionsParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
}

type ListPositionsRow struct {
	InstrumentID      int64
	Quantity          decimal.Decimal
	AvgEntryPrice     decimal.Decimal
	RealizedPnl       decimal.Decimal
	LastEventTime     time.Time
	LastVenueSequence int64
	LastVenueEventID  string
}

func (q *Queries) ListPositions(ctx context.Context, arg ListPositionsParams) ([]ListPositionsRow, error) {
	rows, err := q.db.Query(ctx, listPositions, arg.AccountID, arg.IntegrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionsRow{}
	for rows.Next() {
		var i ListPositionsRow
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Quantity,
			&i.AvgEntryPrice,
			&i.RealizedPnl,
			&i.LastEventTime,
			&i.LastVenueSequence,
			&i.LastVenueEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPosition = `-- name: UpsertPosition :exec
INSERT INTO positions (
  account_id, integration_id, instrument_id, quantity, avg_entry_price, realized_pnl,
  last_event_time, last_venue_sequence, last_venue_event_id
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9
)
ON CONFLICT (integration_id, instrument_id) DO UPDATE SET
  quantity            = EXCLUDED.quantity,
  avg_entry_price     = EXCLUDED.avg_entry_price,
  realized_pnl        = EXCLUDED.realized_pnl,
  last_event_time     = EXCLUDED.last_event_time,
  last_venue_sequence = EXCLUDED.last_venue_sequence,
  last_venue_event_id = EXCLUDED.last_venue_event_id,
  updated_at          = now()
`

type UpsertPositionParams struct {
	AccountID         uuid.UUID
	IntegrationID     uuid.UUID
	InstrumentID      int64
	Quantity          decimal.Decimal
	AvgEntryPrice     decimal.Decimal
	RealizedPnl       decimal.Decimal
	LastEventTime     time.Time
	LastVenueSequence int64
	LastVenueEventID  string
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) error {
	_, err := q.db.Exec(ctx, upsertPosition,
		arg.AccountID,
		arg.IntegrationID,
		arg.InstrumentID,
		arg.Quantity,
		arg.AvgEntryPrice,
		arg.RealizedPnl,
		arg.LastEventTime,
		arg.LastVenueSequence,
		arg.LastVenueEventID,
	)
	return err
}

const upsertProjectionCursor = `-- name: UpsertProjectionCursor :exec
INSERT INTO projection_cursors (
  account_id, integration_id, last_event_time, last_venue_sequence, last_venue_event_id,
  projected_count
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6
)
ON CONFLICT (integration_id) DO UPDATE SET
  last_event_time     = EXCLUDED.last_event_time,
  last_venue_sequence = EXCLUDED.last_venue_sequence,
  last_venue_event_id = EXCLUDED.last_venue_event_id,
  projected_count     = EXCLUDED.projected_count,
  updated_at          = now()
`

type UpsertProjectionCursorParams struct {
	AccountID         uuid.UUID
	IntegrationID     uuid.UUID
	LastEventTime     time.Time
	LastVenueSequence int64
	LastVenueEventID  string
	ProjectedCount    int64
}

func (q *Queries) UpsertProjectionCursor(ctx context.Context, arg UpsertProjectionCursorParams) error {
	_, err := q.db.Exec(ctx, upsertProjectionCursor,
		arg.AccountID,
		arg.IntegrationID,
		arg.LastEventTime,
		arg.LastVenueSequence,
		arg.LastVenueEventID,
		arg.ProjectedCount,
	)
	return err
}
