// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const countPriceTicks = `-- name: CountPriceTicks :one
SELECT count(*) FROM price_ticks WHERE instrument_id = $1
`

func (q *Queries) CountPriceTicks(ctx context.Context, instrumentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceTicks, instrumentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPriceTickAt = `-- name: GetPriceTickAt :one
SELECT instrument_id, ts, price, source, observed_at
FROM price_ticks
WHERE instrument_id = $1
  AND ts <= $2::timestamptz
ORDER BY ts DESC
LIMIT 1
`

type GetPriceTickAtParams struct {
	InstrumentID int64
	At           time.Time
}

// The price in force at an instant: the newest tick at or before it.
//
// At or before, never after. Reaching forward to the next price is look-ahead bias, and in
// a risk product it is the bug that makes a backtest look brilliant and a liquidation
// arrive unannounced.
func (q *Queries) GetPriceTickAt(ctx context.Context, arg GetPriceTickAtParams) (PriceTick, error) {
	row := q.db.QueryRow(ctx, getPriceTickAt, arg.InstrumentID, arg.At)
	var i PriceTick
	err := row.Scan(
		&i.InstrumentID,
		&i.Ts,
		&i.Price,
		&i.Source,
		&i.ObservedAt,
	)
	return i, err
}

const listLatestPriceTicks = `-- name: ListLatestPriceTicks :many
SELECT DISTINCT ON (instrument_id)
       instrument_id, ts, price, source, observed_at
FROM price_ticks
ORDER BY instrument_id, ts DESC
`

// The newest tick per instrument. DISTINCT ON is the one Postgres idiom that answers this
// in a single index-ordered pass rather than a self-join per instrument.
func (q *Queries) ListLatestPriceTicks(ctx context.Context) ([]PriceTick, error) {
	rows, err := q.db.Query(ctx, listLatestPriceTicks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceTick{}
	for rows.Next() {
		var i PriceTick
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Ts,
			&i.Price,
			&i.Source,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPriceTick = `-- name: UpsertPriceTick :exec
INSERT INTO price_ticks (instrument_id, ts, price, source, observed_at)
VALUES ($1, $2, $3, $4,
        $5)
ON CONFLICT (instrument_id, ts) DO UPDATE SET
  price       = EXCLUDED.price,
  source      = EXCLUDED.source,
  observed_at = EXCLUDED.observed_at
WHERE EXCLUDED.observed_at > price_ticks.observed_at
`

type UpsertPriceTickParams struct {
	InstrumentID int64
	Ts           time.Time
	Price        decimal.Decimal
	Source       string
	ObservedAt   time.Time
}

// The minute is the key, so the last price observed in a minute wins. A stream pushing
// every second therefore leaves one row per minute rather than sixty (K7).
//
// The guard on observed_at is what makes that true under an out-of-order frame: a delayed
// push carrying an older observation must not rewind a price the venue never moved back.
func (q *Queries) UpsertPriceTick(ctx context.Context, arg UpsertPriceTickParams) error {
	_, err := q.db.Exec(ctx, upsertPriceTick,
		arg.InstrumentID,
		arg.Ts,
		arg.Price,
		arg.Source,
		arg.ObservedAt,
	)
	return err
}
