// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const listIntegrationStatus = `-- name: ListIntegrationStatus :many
SELECT i.id AS integration_id, i.exchange, i.label, i.status AS configured_status,
       s.state, s.owner_id, s.since, s.updated_at
FROM integrations i
LEFT JOIN integration_status s
  ON s.account_id = i.account_id AND s.integration_id = i.id
WHERE i.account_id = $1
ORDER BY i.created_at, i.id
`

type ListIntegrationStatusRow struct {
	IntegrationID    uuid.UUID
	Exchange         string
	Label            string
	ConfiguredStatus string
	State            *string
	OwnerID          *string
	Since            *time.Time
	UpdatedAt        *time.Time
}

// Every integration the account has, whether or not a worker has ever reported on it: a
// LEFT JOIN rather than a lookup, because an integration with no status row is exactly the
// case a reader must be told about and an inner join would hide it.
func (q *Queries) ListIntegrationStatus(ctx context.Context, accountID uuid.UUID) ([]ListIntegrationStatusRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationStatus, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntegrationStatusRow{}
	for rows.Next() {
		var i ListIntegrationStatusRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.Exchange,
			&i.Label,
			&i.ConfiguredStatus,
			&i.State,
			&i.OwnerID,
			&i.Since,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIntegrationStatus = `-- name: UpsertIntegrationStatus :exec
INSERT INTO integration_status (account_id, integration_id, state, owner_id, since)
VALUES ($1, $2, $3,
        $4, $5)
ON CONFLICT (integration_id) DO UPDATE SET
  state      = EXCLUDED.state,
  owner_id   = EXCLUDED.owner_id,
  since      = CASE WHEN integration_status.state = EXCLUDED.state
                    THEN integration_status.since ELSE EXCLUDED.since END,
  updated_at = now()
`

type UpsertIntegrationStatusParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	State         string
	OwnerID       string
	Since         time.Time
}

// since is only moved when the state actually changes. A worker republishing "degraded"
// every heartbeat must not keep resetting how long it has been degraded -- that would make
// a feed down for an hour report as down for a few seconds, every time anyone looked.
func (q *Queries) UpsertIntegrationStatus(ctx context.Context, arg UpsertIntegrationStatusParams) error {
	_, err := q.db.Exec(ctx, upsertIntegrationStatus,
		arg.AccountID,
		arg.IntegrationID,
		arg.State,
		arg.OwnerID,
		arg.Since,
	)
	return err
}
