// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strategies.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const assignPositionStrategy = `-- name: AssignPositionStrategy :exec
INSERT INTO position_strategies (account_id, integration_id, instrument_id, strategy_id)
VALUES ($1, $2, $3,
        $4)
ON CONFLICT (integration_id, instrument_id) DO UPDATE SET
  strategy_id = EXCLUDED.strategy_id,
  assigned_at = now()
`

type AssignPositionStrategyParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	InstrumentID  int64
	StrategyID    uuid.UUID
}

// Replaces rather than accumulates: the primary key is the position, so a second assignment
// for the same position is the same row (K13 -- one strategy per position in V1).
func (q *Queries) AssignPositionStrategy(ctx context.Context, arg AssignPositionStrategyParams) error {
	_, err := q.db.Exec(ctx, assignPositionStrategy,
		arg.AccountID,
		arg.IntegrationID,
		arg.InstrumentID,
		arg.StrategyID,
	)
	return err
}

const clearPositionStrategy = `-- name: ClearPositionStrategy :exec
DELETE FROM position_strategies
WHERE account_id = $1
  AND integration_id = $2
  AND instrument_id = $3
`

type ClearPositionStrategyParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	InstrumentID  int64
}

func (q *Queries) ClearPositionStrategy(ctx context.Context, arg ClearPositionStrategyParams) error {
	_, err := q.db.Exec(ctx, clearPositionStrategy, arg.AccountID, arg.IntegrationID, arg.InstrumentID)
	return err
}

const createStrategy = `-- name: CreateStrategy :one
INSERT INTO strategies (account_id, name, kind)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateStrategyParams struct {
	AccountID uuid.UUID
	Name      string
	Kind      string
}

// account_id is the primary defence (L12); RLS is the backstop underneath it.
func (q *Queries) CreateStrategy(ctx context.Context, arg CreateStrategyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createStrategy, arg.AccountID, arg.Name, arg.Kind)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPositionStrategies = `-- name: ListPositionStrategies :many
SELECT p.integration_id, p.instrument_id, s.id, s.name, s.kind
FROM position_strategies p
JOIN strategies s ON s.account_id = p.account_id AND s.id = p.strategy_id
WHERE p.account_id = $1
ORDER BY p.integration_id, p.instrument_id
`

type ListPositionStrategiesRow struct {
	IntegrationID uuid.UUID
	InstrumentID  int64
	ID            uuid.UUID
	Name          string
	Kind          string
}

// Every tagged position for one account, with the strategy it belongs to, so a risk response
// groups its positions in one read rather than one per position.
func (q *Queries) ListPositionStrategies(ctx context.Context, accountID uuid.UUID) ([]ListPositionStrategiesRow, error) {
	rows, err := q.db.Query(ctx, listPositionStrategies, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionStrategiesRow{}
	for rows.Next() {
		var i ListPositionStrategiesRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.InstrumentID,
			&i.ID,
			&i.Name,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategies = `-- name: ListStrategies :many
SELECT s.id, s.name, s.kind, s.created_at,
       COUNT(p.instrument_id)::bigint AS positions
FROM strategies s
LEFT JOIN position_strategies p
       ON p.account_id = s.account_id AND p.strategy_id = s.id
WHERE s.account_id = $1
GROUP BY s.id, s.name, s.kind, s.created_at
ORDER BY s.name
`

type ListStrategiesRow struct {
	ID        uuid.UUID
	Name      string
	Kind      string
	CreatedAt time.Time
	Positions int64
}

func (q *Queries) ListStrategies(ctx context.Context, accountID uuid.UUID) ([]ListStrategiesRow, error) {
	rows, err := q.db.Query(ctx, listStrategies, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStrategiesRow{}
	for rows.Next() {
		var i ListStrategiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.Positions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const positionExists = `-- name: PositionExists :one
SELECT EXISTS (
  SELECT 1 FROM positions
  WHERE account_id = $1
    AND integration_id = $2
    AND instrument_id = $3
)
`

type PositionExistsParams struct {
	AccountID     uuid.UUID
	IntegrationID uuid.UUID
	InstrumentID  int64
}

// Tagging something that does not exist is a 404 rather than a row nobody can ever read: the
// tag would sit there until the position appeared, and then apply to it silently.
func (q *Queries) PositionExists(ctx context.Context, arg PositionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, positionExists, arg.AccountID, arg.IntegrationID, arg.InstrumentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
