// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const deleteTransferLink = `-- name: DeleteTransferLink :execrows
DELETE FROM transfer_links
 WHERE account_id = $1 AND id = $2
`

type DeleteTransferLinkParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

// Unjoins two legs. Allowed, unlike deleting a finding: a link is an assertion about two
// events, not a record of what happened, and a user who joined the wrong two must be able to
// say so. The events themselves are untouched (L2).
func (q *Queries) DeleteTransferLink(ctx context.Context, arg DeleteTransferLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransferLink, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransferLegForLinking = `-- name: GetTransferLegForLinking :one
SELECT e.seq, e.integration_id, e.event_type, e.asset_id, e.quantity, e.event_time
  FROM ledger_events e
 WHERE e.account_id = $1
   AND e.seq = $2
   AND e.event_type = $3
`

type GetTransferLegForLinkingParams struct {
	AccountID uuid.UUID
	Seq       int64
	EventType string
}

type GetTransferLegForLinkingRow struct {
	Seq           int64
	IntegrationID uuid.UUID
	EventType     string
	AssetID       *int64
	Quantity      decimal.NullDecimal
	EventTime     time.Time
}

// One leg, confirmed to belong to the caller and to be the direction they claim. The manual
// endpoint reads both halves through this before writing, so a user cannot join an event that
// is not theirs -- RLS would already return nothing, and this turns that nothing into a 404
// rather than a foreign key error the caller has to interpret.
func (q *Queries) GetTransferLegForLinking(ctx context.Context, arg GetTransferLegForLinkingParams) (GetTransferLegForLinkingRow, error) {
	row := q.db.QueryRow(ctx, getTransferLegForLinking, arg.AccountID, arg.Seq, arg.EventType)
	var i GetTransferLegForLinkingRow
	err := row.Scan(
		&i.Seq,
		&i.IntegrationID,
		&i.EventType,
		&i.AssetID,
		&i.Quantity,
		&i.EventTime,
	)
	return i, err
}

const insertTransferLink = `-- name: InsertTransferLink :exec
INSERT INTO transfer_links (account_id, out_seq, in_seq, method)
VALUES ($1, $2, $3, $4)
`

type InsertTransferLinkParams struct {
	AccountID uuid.UUID
	OutSeq    int64
	InSeq     int64
	Method    string
}

// Joins two legs. The unique constraints on out_seq and in_seq mean a second attempt to claim
// either half fails rather than quietly winning, which is the whole point of them.
func (q *Queries) InsertTransferLink(ctx context.Context, arg InsertTransferLinkParams) error {
	_, err := q.db.Exec(ctx, insertTransferLink,
		arg.AccountID,
		arg.OutSeq,
		arg.InSeq,
		arg.Method,
	)
	return err
}

const listTransferLinks = `-- name: ListTransferLinks :many
SELECT l.id, l.method, l.linked_at,
       o.seq AS out_seq, oi.exchange AS out_exchange, o.quantity AS out_quantity,
       o.event_time AS out_event_time,
       d.seq AS in_seq,  di.exchange AS in_exchange,  d.quantity AS in_quantity,
       d.event_time AS in_event_time,
       a.canonical_symbol
  FROM transfer_links l
  JOIN ledger_events o ON o.seq = l.out_seq
  JOIN ledger_events d ON d.seq = l.in_seq
  JOIN integrations oi ON oi.id = o.integration_id
  JOIN integrations di ON di.id = d.integration_id
  JOIN assets a ON a.id = o.asset_id
 WHERE l.account_id = $1
 ORDER BY l.linked_at DESC
`

type ListTransferLinksRow struct {
	ID              uuid.UUID
	Method          string
	LinkedAt        time.Time
	OutSeq          int64
	OutExchange     string
	OutQuantity     decimal.NullDecimal
	OutEventTime    time.Time
	InSeq           int64
	InExchange      string
	InQuantity      decimal.NullDecimal
	InEventTime     time.Time
	CanonicalSymbol string
}

// Every joined movement, newest first, with both halves' own numbers so a reader can see the
// network fee as the difference rather than being told it.
func (q *Queries) ListTransferLinks(ctx context.Context, accountID uuid.UUID) ([]ListTransferLinksRow, error) {
	rows, err := q.db.Query(ctx, listTransferLinks, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransferLinksRow{}
	for rows.Next() {
		var i ListTransferLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.LinkedAt,
			&i.OutSeq,
			&i.OutExchange,
			&i.OutQuantity,
			&i.OutEventTime,
			&i.InSeq,
			&i.InExchange,
			&i.InQuantity,
			&i.InEventTime,
			&i.CanonicalSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlinkedTransferLegs = `-- name: ListUnlinkedTransferLegs :many
SELECT e.seq, e.integration_id, i.exchange, a.canonical_symbol, e.quantity,
       e.event_type, e.event_time, e.raw
  FROM ledger_events e
  JOIN integrations i ON i.id = e.integration_id
  JOIN assets a ON a.id = e.asset_id
 WHERE e.account_id = $1
   AND e.event_type IN ('DEPOSIT', 'WITHDRAWAL')
   AND e.asset_id IS NOT NULL
   AND NOT EXISTS (
         SELECT 1 FROM transfer_links l
          WHERE l.out_seq = e.seq OR l.in_seq = e.seq)
 ORDER BY e.event_time, e.seq
`

type ListUnlinkedTransferLegsRow struct {
	Seq             int64
	IntegrationID   uuid.UUID
	Exchange        string
	CanonicalSymbol string
	Quantity        decimal.NullDecimal
	EventType       string
	EventTime       time.Time
	Raw             []byte
}

// Every withdrawal and deposit this account holds that is not already half of a transfer.
//
// Both directions in one query, tagged by event_type, because the matcher needs them together
// and two queries would be two instants -- a leg linked between them would be offered twice.
//
// The NOT EXISTS is what makes a re-run idempotent: a leg already joined is not a candidate,
// so matching twice produces the same links rather than a duplicate-key error.
func (q *Queries) ListUnlinkedTransferLegs(ctx context.Context, accountID uuid.UUID) ([]ListUnlinkedTransferLegsRow, error) {
	rows, err := q.db.Query(ctx, listUnlinkedTransferLegs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnlinkedTransferLegsRow{}
	for rows.Next() {
		var i ListUnlinkedTransferLegsRow
		if err := rows.Scan(
			&i.Seq,
			&i.IntegrationID,
			&i.Exchange,
			&i.CanonicalSymbol,
			&i.Quantity,
			&i.EventType,
			&i.EventTime,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
