// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: valuation.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const countValuationRuns = `-- name: CountValuationRuns :one
SELECT count(*) FROM valuation_runs
`

func (q *Queries) CountValuationRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countValuationRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAssetIDBySymbol = `-- name: GetAssetIDBySymbol :one
SELECT id FROM assets WHERE canonical_symbol = $1
`

// The canonical registry is keyed by symbol for exactly this: configuration names assets
// the way a human does, and the id it resolves to is a database detail.
func (q *Queries) GetAssetIDBySymbol(ctx context.Context, canonicalSymbol string) (int64, error) {
	row := q.db.QueryRow(ctx, getAssetIDBySymbol, canonicalSymbol)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLatestValuationRun = `-- name: GetLatestValuationRun :one
SELECT id, as_of, numeraire, price_source, assumed_peg, oldest_observed_at, created_at
FROM valuation_runs
WHERE as_of <= $1::timestamptz
ORDER BY as_of DESC, id DESC
LIMIT 1
`

// The newest run at or before an instant.
//
// At or before, never after: a response for a past instant must not be built on prices
// from after it. That is look-ahead bias, and in a risk product it is the bug that makes a
// backtest look brilliant.
func (q *Queries) GetLatestValuationRun(ctx context.Context, at time.Time) (ValuationRun, error) {
	row := q.db.QueryRow(ctx, getLatestValuationRun, at)
	var i ValuationRun
	err := row.Scan(
		&i.ID,
		&i.AsOf,
		&i.Numeraire,
		&i.PriceSource,
		&i.AssumedPeg,
		&i.OldestObservedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertValuationPrice = `-- name: InsertValuationPrice :exec
INSERT INTO valuation_prices (run_id, asset_id, price_usd, path, assumed_peg, observed_at)
VALUES ($1, $2, $3, $4,
        $5, $6)
`

type InsertValuationPriceParams struct {
	RunID      int64
	AssetID    int64
	PriceUsd   decimal.Decimal
	Path       []byte
	AssumedPeg bool
	ObservedAt *time.Time
}

func (q *Queries) InsertValuationPrice(ctx context.Context, arg InsertValuationPriceParams) error {
	_, err := q.db.Exec(ctx, insertValuationPrice,
		arg.RunID,
		arg.AssetID,
		arg.PriceUsd,
		arg.Path,
		arg.AssumedPeg,
		arg.ObservedAt,
	)
	return err
}

const insertValuationRun = `-- name: InsertValuationRun :one
INSERT INTO valuation_runs (as_of, price_source, assumed_peg, oldest_observed_at)
VALUES ($1, $2, $3,
        $4)
RETURNING id
`

type InsertValuationRunParams struct {
	AsOf             time.Time
	PriceSource      string
	AssumedPeg       bool
	OldestObservedAt *time.Time
}

func (q *Queries) InsertValuationRun(ctx context.Context, arg InsertValuationRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertValuationRun,
		arg.AsOf,
		arg.PriceSource,
		arg.AssumedPeg,
		arg.OldestObservedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAssetIDs = `-- name: ListAssetIDs :many
SELECT id FROM assets ORDER BY id
`

// Every asset in the registry. A run prices all of them rather than only the ones some
// account holds, because a run belongs to no account (00019) -- and because an asset that
// was unpriceable is worth recording as unpriceable exactly once, not once per reader.
func (q *Queries) ListAssetIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAssetIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricedPairs = `-- name: ListPricedPairs :many
SELECT DISTINCT ON (p.instrument_id)
       p.instrument_id, i.base_asset_id, i.quote_asset_id, p.price, p.observed_at
FROM price_ticks p
JOIN instruments i ON i.id = p.instrument_id
WHERE p.ts <= $1::timestamptz
ORDER BY p.instrument_id, p.ts DESC
`

type ListPricedPairsRow struct {
	InstrumentID int64
	BaseAssetID  int64
	QuoteAssetID int64
	Price        decimal.Decimal
	ObservedAt   time.Time
}

// Every instrument that has a price, with the two assets it connects and the newest tick
// for it. This is the graph the valuation walk runs over.
//
// DISTINCT ON is the one Postgres idiom that takes the newest row per instrument in a
// single index-ordered pass rather than a self-join per instrument.
func (q *Queries) ListPricedPairs(ctx context.Context, at time.Time) ([]ListPricedPairsRow, error) {
	rows, err := q.db.Query(ctx, listPricedPairs, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPricedPairsRow{}
	for rows.Next() {
		var i ListPricedPairsRow
		if err := rows.Scan(
			&i.InstrumentID,
			&i.BaseAssetID,
			&i.QuoteAssetID,
			&i.Price,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValuationPrices = `-- name: ListValuationPrices :many
SELECT asset_id, price_usd, path, assumed_peg, observed_at
FROM valuation_prices
WHERE run_id = $1
ORDER BY asset_id
`

type ListValuationPricesRow struct {
	AssetID    int64
	PriceUsd   decimal.Decimal
	Path       []byte
	AssumedPeg bool
	ObservedAt *time.Time
}

func (q *Queries) ListValuationPrices(ctx context.Context, runID int64) ([]ListValuationPricesRow, error) {
	rows, err := q.db.Query(ctx, listValuationPrices, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListValuationPricesRow{}
	for rows.Next() {
		var i ListValuationPricesRow
		if err := rows.Scan(
			&i.AssetID,
			&i.PriceUsd,
			&i.Path,
			&i.AssumedPeg,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
